CodeSystem: PLMedicalEntityCellTypeCS
Id:	pl-medicalEntityCellType-CS
Title: "Specjalność komórki organizacyjnej (PL)"
Description: "Specjalność komórki organizacyjnej podmiotu medycznego (cz. VIII SKR)"
* ^url = "http://hl7.org.pl/fhir/CodeSystem/pl-medicalEntityCellType-CS"
* #0010 "Poradnia (gabinet) lekarza podstawowej opieki zdrowotnej"
* #0012 "Poradnia (gabinet) podstawowej opieki zdrowotnej"
* #0014 "Poradnia (gabinet) lekarza rodzinnego"
* #0016 "Poradnia (gabinet) nocnej i świątecznej opieki zdrowotnej"
* #0020 "Punkt felczerski"
* #0032 "Poradnia (gabinet) pielęgniarki podstawowej opieki zdrowotnej"
* #0034 "Poradnia (gabinet) położnej podstawowej opieki zdrowotnej"
* #0036 "Poradnia (gabinet) pielęgniarki rodzinnej"
* #0038 "Poradnia (gabinet) położnej rodzinnej"
* #0040 "Gabinet profilaktyki zdrowotnej i pomocy przedlekarskiej"
* #1000 "Poradnia chorób wewnętrznych"
* #1008 "Poradnia chorób metabolicznych"
* #1010 "Poradnia alergologiczna"
* #1020 "Poradnia diabetologiczna"
* #1022 "Poradnia leczenia zespołu stopy cukrzycowej"
* #1024 "Poradnia leczenia ran przewlekłych"
* #1027 "Poradnia endokrynologii i diabetologii dziecięcej"
* #1030 "Poradnia endokrynologiczna"
* #1032 "Poradnia endokrynologiczno-ginekologiczna"
* #1034 "Poradnia andrologiczna"
* #1036 "Poradnia leczenia niepłodności"
* #1038 "Poradnia chorób tarczycy"
* #1040 "Poradnia endokrynologiczna osteoporozy"
* #1050 "Poradnia gastroenterologiczna"
* #1056 "Poradnia hepatologiczna"
* #1060 "Poradnia geriatryczna"
* #1070 "Poradnia hematologiczna"
* #1072 "Poradnia nowotworów krwi"
* #1080 "Poradnia immunologiczna"
* #1100 "Poradnia kardiologiczna"
* #1102 "Poradnia wad serca"
* #1104 "Poradnia nadciśnienia tętniczego"
* #1120 "Poradnia chorób naczyń"
* #1130 "Poradnia nefrologiczna"
* #1150 "Poradnia toksykologiczna"
* #1160 "Poradnia medycyny pracy"
* #1180 "Poradnia medycyny paliatywnej"
* #1200 "Poradnia dermatologiczna"
* #1202 "Poradnia wenerologiczna"
* #1210 "Poradnia genetyczna"
* #1212 "Poradnia genetyczno-onkologiczna"
* #1220 "Poradnia neurologiczna"
* #1222 "Poradnia leczenia bólu"
* #1240 "Poradnia onkologiczna"
* #1242 "Poradnia chemioterapii"
* #1244 "Poradnia radioterapii"
* #1249 "Poradnia onkologii i hematologii dziecięcej"
* #1250 "Poradnia medycyny nuklearnej"
* #1270 "Poradnia gruźlicy i chorób płuc"
* #1272 "Poradnia chorób płuc"
* #1276 "Poradnia leczenia mukowiscydozy"
* #1280 "Poradnia reumatologiczna"
* #1300 "Poradnia rehabilitacyjna"
* #1302 "Poradnia rehabilitacji narządu ruchu"
* #1304 "Poradnia zaopatrzenia ortopedycznego"
* #1306 "Poradnia rehabilitacji neurologicznej"
* #1308 "Poradnia rehabilitacji kardiologicznej"
* #1310 "Dział (pracownia) fizjoterapii"
* #1312 "Dział (pracownia) fizykoterapii"
* #1314 "Dział (pracownia) kinezyterapii"
* #1316 "Dział (pracownia) hydroterapii"
* #1318 "Dział (pracownia) krioterapii"
* #1320 "Dział (pracownia) masażu leczniczego"
* #1330 "Dział (pracownia) balneoterapii"
* #1340 "Poradnia chorób zakaźnych"
* #1342 "Poradnia profilaktyczno-lecznicza (HIV/AIDS)"
* #1346 "Poradnia chorób tropikalnych"
* #1348 "Poradnia chorób odzwierzęcych i pasożytniczych"
* #1370 "Poradnia medycyny sportowej"
* #1390 "Poradnia leczenia obrzęku limfatycznego"
* #1401 "Poradnia pediatryczna"
* #1405 "Poradnia zaburzeń i wad rozwojowych dzieci"
* #1409 "Poradnia pediatryczna szczepień dla dzieci z grup wysokiego ryzyka"
* #1421 "Poradnia neonatologiczna"
* #1450 "Poradnia położniczo-ginekologiczna"
* #1452 "Poradnia ginekologiczna"
* #1453 "Poradnia ginekologiczna dla dziewcząt"
* #1454 "Poradnia patologii ciąży"
* #1458 "Poradnia profilaktyki chorób piersi"
* #1460 "Poradnia ginekologii onkologicznej"
* #1470 "Poradnia planowania rodziny i rozrodczości"
* #1472 "Szkoła rodzenia"
* #1474 "Poradnia laktacyjna"
* #1500 "Poradnia chirurgii ogólnej"
* #1506 "Poradnia proktologiczna"
* #1520 "Poradnia chirurgii klatki piersiowej"
* #1530 "Poradnia chirurgii naczyniowej"
* #1540 "Poradnia chirurgii onkologicznej"
* #1550 "Poradnia chirurgii plastycznej"
* #1552 "Poradnia chirurgii ręki"
* #1554 "Poradnia leczenia oparzeń"
* #1560 "Poradnia kardiochirurgiczna"
* #1562 "Poradnia kontroli rozruszników i kardiowerterów"
* #1570 "Poradnia neurochirurgiczna"
* #1572 "Poradnia kontroli systemów neuromodulacji"
* #1580 "Poradnia chirurgii urazowo-ortopedycznej"
* #1583 "Poradnia wad postawy"
* #1584 "Poradnia osteoporozy"
* #1587 "Poradnia preluksacyjna"
* #1600 "Poradnia okulistyczna"
* #1604 "Poradnia leczenia zeza"
* #1610 "Poradnia otorynolaryngologiczna"
* #1612 "Poradnia audiologiczna"
* #1614 "Poradnia foniatryczna"
* #1616 "Poradnia logopedyczna"
* #1630 "Poradnia chirurgii szczękowo-twarzowej"
* #1640 "Poradnia urologiczna"
* #1642 "Ambulatoryjna stacja dializ"
* #1650 "Poradnia transplantologiczna"
* #1670 "Poradnia anestezjologiczna"
* #1700 "Poradnia zdrowia psychicznego"
* #1704 "Poradnia psychogeriatryczna"
* #1706 "Poradnia leczenia nerwic"
* #1708 "Poradnia dla osób z autyzmem dziecięcym"
* #1710 "Poradnia psychosomatyczna"
* #1740 "Poradnia leczenia uzależnień"
* #1742 "Poradnia antynikotynowa"
* #1744 "Poradnia terapii uzależnienia od alkoholu i współuzależnienia"
* #1746 "Poradnia terapii uzależnienia od substancji psychoaktywnych"
* #1750 "Poradnia promocji zdrowia psychicznego"
* #1780 "Poradnia seksuologiczna i patologii współżycia"
* #1790 "Poradnia psychologiczna"
* #1800 "Poradnia stomatologiczna"
* #1810 "Poradnia periodontologiczna oraz chorób błon śluzowych przyzębia"
* #1820 "Poradnia ortodontyczna"
* #1830 "Poradnia protetyki stomatologicznej"
* #1840 "Poradnia chirurgii stomatologicznej"
* #1850 "Poradnia uzdrowiskowa"
* #1860 "Poradnia domowego leczenia tlenem"
* #1870 "Poradnia żywieniowa"
* #2130 "Zespół domowej dializoterapii otrzewnowej"
* #2140 "Zespół długoterminowej opieki domowej"
* #2142 "Pielęgniarska opieka długoterminowa domowa"
* #2146 "Zespół rehabilitacji domowej"
* #2180 "Hospicjum domowe/ Zespół domowej opieki paliatywnej"
* #2182 "Dzienny ośrodek opieki paliatywnej lub hospicyjnej"
* #2184 "Hospicjum stacjonarne /Stacjonarny ośrodek opieki paliatywnej"
* #2200 "Dzienny ośrodek opieki geriatrycznej"
* #2202 "Geriatryczny zespół opieki domowej"
* #2300 "Zakład/Ośrodek rehabilitacji leczniczej dziennej"
* #2302 "Zakład/Ośrodek rehabilitacji kardiologicznej"
* #2304 "Zakład/Ośrodek rehabilitacji pulmonologicznej"
* #2306 "Zakład/Ośrodek rehabilitacji leczniczej"
* #2308 "Zakład/Ośrodek rehabilitacji kardiologicznej dziennej"
* #2310 "Zakład/Ośrodek rehabilitacji pulmonologicznej dziennej"
* #2312 "Zakład/Ośrodek rehabilitacji neurologicznej dziennej"
* #2314 "Zakład/Ośrodek rehabilitacji neurologicznej"
* #2400 "Izba chorych"
* #2700 "Oddział dzienny psychiatryczny (ogólny)"
* #2702 "Oddział dzienny psychiatryczny rehabilitacyjny"
* #2704 "Oddział dzienny psychogeriatryczny"
* #2706 "Oddział dzienny zaburzeń nerwicowych"
* #2708 "Oddział dzienny dla osób z autyzmem dziecięcym"
* #2710 "Oddział/Ośrodek alzheimerowski"
* #2712 "Oddział dzienny terapii uzależnienia od alkoholu"
* #2714 "Oddział dzienny terapii uzależnienia od substancji psychoaktywnych"
* #2720 "Hostel dla osób z zaburzeniami psychicznymi"
* #2724 "Hostel dla uzależnionych od alkoholu"
* #2726 "Hostel dla uzależnionych od substancji psychoaktywnych"
* #2730 "Zespół leczenia środowiskowego (domowego)"
* #2732 "Opieka domowa, rodzinna"
* #2734 "Zespół leczenia środowiskowego (domowego) dla osób z autyzmem"
* #2740 "Ośrodek leczenia uzależnień bliżej niescharakteryzowanych"
* #2742 "Ośrodek leczenia uzależnień stacjonarny"
* #2744 "Ośrodek terapii uzależnienia od alkoholu"
* #2746 "Ośrodek terapii uzależnienia od substancji psychoaktywnych"
* #2748 "Ośrodek leczenia alkoholowych zespołów abstynencyjnych (detoksykacji)"
* #2750 "Ośrodek leczenia zespołów abstynencyjnych po substancjach psychoaktywnych (detoksykacji)"
* #2752 "Ośrodek rehabilitacyjny dla uzależnionych od substancji psychoaktywnych"
* #2754 "Ośrodek terapii dla uzależnionych od alkoholu ze współistniejącymi zaburzeniami psychotycznymi"
* #2756 "Ośrodek terapii dla uzależnionych od substancji psychoaktywnych ze współistniejącymi zaburzeniami psychotycznymi"
* #2758 "Ośrodek rehabilitacji dla uzależnionych od substancji psychoaktywnych ze współistniejącymi zaburzeniami psychotycznymi"
* #2800 "Ośrodek opieki medycznej dzienny"
* #3010 "Ambulatorium ogólne"
* #3012 "Ambulatorium chirurgiczne"
* #3016 "Ambulatorium okulistyczne"
* #3040 "Ambulatorium stomatologiczne"
* #3112 "Zespół ratownictwa medycznego podstawowy"
* #3114 "Zespół ratownictwa medycznego specjalistyczny"
* #3118 "Wyjazdowy zespół sanitarny typu N"
* #3152 "Wodny zespół ratownictwa medycznego podstawowy"
* #3154 "Wodny zespół ratownictwa medycznego specjalistyczny"
* #3200 "Lotniczy zespół transportu sanitarnego"
* #3210 "Lotniczy zespół ratownictwa medycznego"
* #4000 "Oddział chorób wewnętrznych"
* #4002 "Oddział wieloprofilowy zachowawczy"
* #4008 "Oddział chorób metabolicznych"
* #4010 "Oddział alergologiczny"
* #4020 "Oddział diabetologiczny"
* #4030 "Oddział endokrynologiczny"
* #4050 "Oddział gastroenterologiczny"
* #4060 "Oddział geriatryczny"
* #4070 "Oddział hematologiczny"
* #4072 "Oddział nowotworów krwi"
* #4080 "Oddział immunologii klinicznej"
* #4100 "Oddział kardiologiczny"
* #4106 "Oddział intensywnego nadzoru kardiologicznego"
* #4120 "Oddział angiologiczny"
* #4122 "Oddział hipertensjologiczny"
* #4130 "Oddział nefrologiczny"
* #4132 "Stacja dializ"
* #4140 "Oddział medycyny nuklearnej"
* #4150 "Oddział toksykologiczny"
* #4170 "Oddział dla przewlekle chorych"
* #4180 "Oddział medycyny paliatywnej"
* #4200 "Oddział dermatologiczny"
* #4220 "Oddział neurologiczny"
* #4222 "Oddział udarowy"
* #4240 "Oddział onkologiczny"
* #4242 "Oddział onkologii klinicznej/chemioterapii"
* #4244 "Oddział radioterapii"
* #4249 "Oddział onkologii i hematologii dziecięcej"
* #4260 "Oddział anestezjologii i intensywnej terapii"
* #4270 "Oddział gruźlicy i chorób płuc"
* #4272 "Oddział chorób płuc"
* #4274 "Oddział leczenia gruźlicy"
* #4280 "Oddział reumatologiczny"
* #4300 "Oddział rehabilitacyjny"
* #4302 "Oddział rehabilitacji narządu ruchu"
* #4304 "Oddział paraplegii i tetraplegii"
* #4306 "Oddział rehabilitacji neurologicznej"
* #4308 "Oddział rehabilitacji kardiologicznej"
* #4310 "Oddział rehabilitacji pulmonologicznej"
* #4340 "Oddział chorób zakaźnych"
* #4342 "Oddział leczenia AIDS"
* #4346 "Oddział chorób tropikalnych"
* #4348 "Oddział obserwacyjno-zakaźny"
* #4350 "Oddział chorób zawodowych"
* #4401 "Oddział pediatryczny"
* #4403 "Oddział niemowlęcy"
* #4421 "Oddział neonatologiczny"
* #4450 "Oddział położniczo-ginekologiczny"
* #4452 "Oddział ginekologiczny"
* #4454 "Oddział patologii ciąży"
* #4456 "Oddział położniczy"
* #4458 "Oddział położnictwa i neonatologii"
* #4460 "Oddział ginekologii onkologicznej"
* #4500 "Oddział chirurgiczny ogólny"
* #4510 "Oddział wieloprofilowy zabiegowy"
* #4520 "Oddział chirurgii klatki piersiowej"
* #4530 "Oddział chirurgii naczyniowej"
* #4540 "Oddział chirurgii onkologicznej"
* #4550 "Oddział chirurgii plastycznej"
* #4554 "Oddział leczenia oparzeń"
* #4560 "Oddział kardiochirurgiczny"
* #4570 "Oddział neurochirurgiczny"
* #4580 "Oddział chirurgii urazowo-ortopedycznej"
* #4590 "Oddział obrażeń wielonarządowych"
* #4600 "Oddział okulistyczny"
* #4610 "Oddział otorynolaryngologiczny"
* #4620 "Oddział audiologiczno-foniatryczny"
* #4630 "Oddział chirurgii szczękowo-twarzowej"
* #4640 "Oddział urologiczny"
* #4650 "Oddział transplantologiczny"
* #4652 "Oddział transplantacji nerek"
* #4654 "Oddział transplantacji wątroby"
* #4656 "Oddział transplantacji serca"
* #4658 "Oddział transplantacji szpiku"
* #4660 "Oddział transplantacji trzustki"
* #4662 "Oddział transplantacji płuc"
* #4670 "Oddział leczenia jednego dnia"
* #4700 "Oddział psychiatryczny (ogólny)"
* #4702 "Oddział rehabilitacji psychiatrycznej"
* #4704 "Oddział leczenia zaburzeń nerwicowych"
* #4710 "Oddział psychiatryczny dla chorych somatycznie"
* #4712 "Oddział psychogeriatryczny"
* #4714 "Oddział psychiatryczny dla chorych na gruźlicę"
* #4716 "Oddział psychiatryczny dla przewlekle chorych"
* #4730 "Oddział psychiatrii sądowej"
* #4732 "Oddział psychiatrii sądowej o wzmocnionym zabezpieczeniu"
* #4734 "Oddział psychiatrii sądowej o maksymalnym zabezpieczeniu"
* #4736 "Oddział odwykowy o wzmocnionym zabezpieczeniu"
* #4740 "Oddział leczenia uzależnień"
* #4742 "Oddział leczenia alkoholowych zespołów abstynencyjnych (detoksykacji)"
* #4744 "Oddział terapii uzależnienia od alkoholu"
* #4746 "Oddział terapii uzależnienia od substancji psychoaktywnych"
* #4748 "Oddział leczenia zespołów abstynencyjnych po substancjach psychoaktywnych (detoksykacji)"
* #4750 "Oddział rehabilitacyjny dla uzależnionych od substancji psychoaktywnych"
* #4752 "Oddział terapii dla uzależnionych od alkoholu ze współistniejącymi zaburzeniami psychotycznymi"
* #4754 "Oddział terapii dla uzależnionych od substancji psychoaktywnych ze współistniejącymi zaburzeniami psychotycznymi"
* #4756 "Oddział rehabilitacji dla uzależnionych od substancji psychoaktywnych ze współistniejącymi zaburzeniami psychotycznymi"
* #4840 "Oddział chirurgii stomatologicznej"
* #4900 "Izba przyjęć szpitala"
* #4902 "Szpitalny oddział ratunkowy"
* #4910 "Blok operacyjny"
* #4912 "Sala porodowa"
* #4922 "Apteka szpitalna albo zakładowa"
* #4924 "Dział farmacji"
* #4950 "Oddział anestezjologii"
* #5160 "Zakład/Oddział pielęgnacyjno-opiekuńczy"
* #5162 "Zakład/Oddział pielęgnacyjno-opiekuńczy psychiatryczny"
* #5170 "Zakład/Oddział opiekuńczo-leczniczy"
* #5172 "Zakład/Oddział opiekuńczo-leczniczy psychiatryczny"
* #5260 "Zakład/Oddział dzienny pielęgnacyjno-opiekuńczy psychiatryczny"
* #5272 "Zakład/Oddział dzienny opiekuńczo-leczniczy psychiatryczny"
* #5360 "Zespół opieki domowej przy zakładzie/oddziale pielęgnacyjno-opiekuńczym lub opiekuńczo-leczniczym psychiatrycznym"
* #6100 "Oddział uzdrowiskowy szpitalny"
* #6200 "Oddział uzdrowiskowy szpitalny w urządzonym podziemnym wyrobisku górniczym"
* #6300 "Oddział uzdrowiskowy rehabilitacji szpitalnej"
* #6500 "Oddział uzdrowiskowy sanatoryjny"
* #6600 "Oddział uzdrowiskowy sanatoryjny w urządzonym podziemnym wyrobisku górniczym"
* #6700 "Oddział uzdrowiskowy rehabilitacji sanatoryjnej"
* #7100 "Medyczne laboratorium diagnostyczne (laboratorium)"
* #7102 "Pracownia genetyczna"
* #7104 "Pracownia toksykologiczna"
* #7110 "Punkt pobrań materiałów do badań"
* #7120 "Pracownia diagnostyki mikrobiologicznej"
* #7130 "Pracownia serologiczna"
* #7140 "Pracownia cytologiczna"
* #7150 "Pracownia histopatologii"
* #7210 "Pracownia USG"
* #7220 "Pracownia tomografii komputerowej"
* #7222 "Pracownia pozytonowej tomografii emisyjnej"
* #7230 "Pracownia radiologii zabiegowej"
* #7232 "Pracownia hemodynamiki"
* #7234 "Pracownia elektrofizjologii"
* #7236 "Pracownia urządzeń wszczepialnych serca"
* #7240 "Pracownia rentgenodiagnostyki ogólnej"
* #7242 "Pracownia mammografii"
* #7244 "Pracownia densytometryczna"
* #7250 "Pracownia rezonansu magnetycznego"
* #7290 "Mobilna pracownia badań diagnostycznych"
* #7300 "Zakład patomorfologii"
* #7400 "Zakład rehabilitacji leczniczej"
* #7500 "Ośrodek terapii hiperbarycznej"
* #7910 "Pracownia endoskopii"
* #7912 "Pracownia urodynamiczna"
* #7920 "Pracownia badań słuchu"
* #7930 "Pracownia dopasowania systemów implantów słuchowych"
* #7950 "Pracownia lub zakład medycyny nuklearnej"
* #7960 "Pracownia lub zakład teleradioterapii"
* #7962 "Pracownia lub zakład brachyterapii"
* #7998 "Inne pracownie diagnostyczne lub zabiegowe"
* #8100 "Pracownia protetyki dentystycznej"
* #8200 "Pracownia lub punkt zaopatrzenia w środki pomocnicze"
* #8210 "Pracownia lub punkt zaopatrzenia w środki wspomagania słuchu"
* #8220 "Pracownia lub punkt zaopatrzenia w środki optyczne"
* #8230 "Pracownia lub punkt zaopatrzenia w wyroby medyczne będące przedmiotami ortopedycznymi"
* #8500 "Bank krwi"
* #8502 "Punkt pobrań krwi"
* #8510 "Bank tkanek i komórek"
* #8512 "Punkt pobrań tkanek i szpiku kostnego"
* #8520 "Dział krwiodawstwa i krwiolecznictwa"
* #9000 "Inna i nieokreślona komórka działalności medycznej"
* #9010 "Pracownia akupresury i akupunktury"
* #9012 "Pracownia ziołolecznictwa"
* #9200 "Dział higieny i epidemiologii"
* #9202 "Dział nadzoru radiologicznego"
* #9204 "Dział nadzoru sanitarnego"
* #9206 "Dział nadzoru zapobiegawczego"
* #9210 "Dział oświaty i promocji zdrowia"
* #9220 "Dział żywności, żywienia i przedmiotów użytku"
* #9230 "Dział orzecznictwa o stanie zdrowia"
* #9250 "Zespół transportu medycznego - świadczenia zdrowotne udzielane w specjalistycznym środku transportu"
* #9400 "Szpitalny zespół wspierający opieki paliatywnej"
* #9450 "Gabinet diagnostyczno-zabiegowy"
* #9600 "Punkt szczepień"
* #9700 "Poradnia promocji zdrowia"
* #9800 "Dyspozytornia medyczna"
