ValueSet: NfzGuaranteedServiceCodeVS
Id: pl-ssidl-nfzGuaranteedServiceCode-VS
Title: "Kody świadczeń gwarantowanych NFZ"
Description: "Kody świadczeń gwarantowanych NFZ"
// Podczas importu z excela:
// - usunąć średniki, przecinki, kropki i spacje na końcu nazwy
// - poprawić formy gramatyczne na mianownik
* $nfz-guaranteed#1.6.2.14 "albumina"
* $nfz-guaranteed#7.1.2.h "albuminuria (stężenie albumin w moczu)"
* $nfz-guaranteed#7.2.2.a "albuminuria (stężenie albumin w moczu)"
* $nfz-guaranteed#5.1.1.9 "aminotransferaza alaninowa (ALT)"
* $nfz-guaranteed#1.6.2.25 "aminotransferaza alaninowa (ALT)"
* $nfz-guaranteed#1.3a.2.1 "aminotransferaza alaninowa (ALAT)"
* $nfz-guaranteed#5.1.1.8 "aminotransferaza asparaginianowa (AST)"
* $nfz-guaranteed#1.6.2.24 "aminotransferaza asparaginianowa (AST)"
* $nfz-guaranteed#1.3a.2.2 "aminotransferaza asparaginianowa (ASPAT)"
* $nfz-guaranteed#1.6.2.27 "amylaza"
* $nfz-guaranteed#5.1.1.19 "amylaza"
* $nfz-guaranteed#1.6a.1.4 "anty-CCP"
* $nfz-guaranteed#1.6.2.33 "antygen HBs-AgHBs"
* $nfz-guaranteed#1.3a.2.5 "anty-HCV"
* $nfz-guaranteed#7.4.2.d "antyTg (przeciwciała przeciw tyreoglobulinie)"
* $nfz-guaranteed#7.4.2.b "antyTPO (przeciwciała przeciw peroksydazie tarczycowej)"
* $nfz-guaranteed#7.4.2.c "antyTSHR (przeciwciała przeciw receptorom TSH)"
* $nfz-guaranteed#1.6a.2 "Badania kału – antygen H pylori w kale"
* $nfz-guaranteed#1.6a.3 "Badania mikrobiologiczne – Strep-test"
* $nfz-guaranteed#1.3a.1.6 "badanie ogólne moczu"
* $nfz-guaranteed#5.1.1.7 "badanie ogólne moczu (profil)"
* $nfz-guaranteed#1.6.4.1 "badanie ogólne"
* $nfz-guaranteed#1.6.2.12 "białko całkowite"
* $nfz-guaranteed#1.6.2.15 "białko C-reaktywne (CRP)"
* $nfz-guaranteed#5.1.1.6 "białko C-reaktywne (CRP)"
* $nfz-guaranteed#1.6.2.22 "bilirubina bezpośrednia"
* $nfz-guaranteed#1.6.2.21 "bilirubina całkowita"
* $nfz-guaranteed#5.1.1.11 "bilirubina całkowita"
* $nfz-guaranteed#7.1.2.g "BNP (NT-pro-BNP)"
* $nfz-guaranteed#1.4.1.1 "cholesterol całkowity"
* $nfz-guaranteed#1.6.2.17 "cholesterol całkowity"
* $nfz-guaranteed#1.4.1.2 "cholesterol HDL"
* $nfz-guaranteed#1.4.1.3 "cholesterol LDL"
* $nfz-guaranteed#1.6.2.18 "cholesterol-HDL"
* $nfz-guaranteed#1.6.2.19 "cholesterol-LDL"
* $nfz-guaranteed#1.4.1.5 "cholesterol nie-HDL (wartość wyliczana)"
* $nfz-guaranteed#1.6a.1.5 "CRP – szybki test ilościowy (dzieci do ukończenia 6 roku życia)"
* $nfz-guaranteed#5.1.1.17 "czas częściowej tromboplastyny po aktywacji (APTT) – czas kaolinowo-kefalinowy"
* $nfz-guaranteed#1.6.5.2 "czas kaolinowo-kefalinowy (APTT)"
* $nfz-guaranteed#1.6.2.30 "czynnik reumatoidalny (RF)"
* $nfz-guaranteed#1.6a.1.1 "ferrytyna"
* $nfz-guaranteed#1.6.5.3 "fibrynogen"
* $nfz-guaranteed#5.1.1.20 "fibrynogen"
* $nfz-guaranteed#1.6.2.29 "fosfataza kwaśna całkowita (ACP)"
* $nfz-guaranteed#1.6.2.23 "fosfataza alkaliczna (ALP)"
* $nfz-guaranteed#1.6.2.35 "FT3"
* $nfz-guaranteed#1.6.2.36 "FT4"
* $nfz-guaranteed#5.1.1.21 "gamma glutamylotranspeptydaza (GGTP)"
* $nfz-guaranteed#1.6.2.26 "gammaglutamylotranspeptydaza (GGTP)"
* $nfz-guaranteed#1.3a.2.3 "gammaglutamylotranspeptydazę (GGTP)"
* $nfz-guaranteed#5.1.1.2 "glukoza z krwi żylnej"
* $nfz-guaranteed#1.6.2.10 "glukoza"
* $nfz-guaranteed#1.6a.1.10 "HIV test przesiewowy (przeciwciała przeciwko anty-HIV i antygen p24)"
* $nfz-guaranteed#1.3a.1.5 "hormon tyreotropowy (TSH)"
* $nfz-guaranteed#1.6.2.32 "hormon tyreotropowy (TSH)"
* $nfz-guaranteed#1.6.3.5 "ilościowe oznaczanie amylazy"
* $nfz-guaranteed#1.6.3.2 "ilościowe oznaczanie białka"
* $nfz-guaranteed#1.6.3.3 "ilościowe oznaczanie glukozy"
* $nfz-guaranteed#1.6.3.4 "ilościowe oznaczanie wapnia"
* $nfz-guaranteed#1.6a.1.7 "immunoglobuliny E całkowite (IgE)"
* $nfz-guaranteed#1.6a.1.9 "immunoglobuliny E swoiste (IgE) z panelem 10-punktowych oznaczeń dotyczącym alergii pokarmowych: pokarmowe: mleko jajko pszenica soja orzechy ziemne orzechy laskowe ryby owoce morza – skorupiaki marchew jabłko"
* $nfz-guaranteed#1.6a.1.8 "immunoglobuliny E swoiste (IgE) z panelem 10-punktowych oznaczeń dotyczącym alergii wziewnych: leszczyna olcha brzoza trawy żyto bylica roztocza kurzu domowego pies kot alternaria"
* $nfz-guaranteed#5.1.1.15 "kinaza fosfokreatynowa izoenzym CK-MB (CKMB)"
* $nfz-guaranteed#1.6.2.28 "kinaza kreatynowa (CK)"
* $nfz-guaranteed#1.6.2.9 "kreatynina"
* $nfz-guaranteed#5.1.1.3 "kreatynina"
* $nfz-guaranteed#1.6.4.3 "krew utajona ‒ metodą immunochemiczną"
* $nfz-guaranteed#5.1.1.16 "kwas moczowy"
* $nfz-guaranteed#1.6.2.16 "kwas moczowy"
* $nfz-guaranteed#1.6.2.8 "mocznik"
* $nfz-guaranteed#5.1.1.10 "mocznik"
* $nfz-guaranteed#1.6a.1.3 "kwas foliowy"
* $nfz-guaranteed#1.3a.1.4 "lipidogram uwzględniający cholesterol całkowity LDL HDL oraz triglicerydy"
* $nfz-guaranteed#1.6.2.31 "miano antystreptolizyn O (ASO)"
* $nfz-guaranteed#5.1.1.1 "morfologia krwi 8-parametrowa"
* $nfz-guaranteed#1.3a.1.1 "morfologia krwi"
* $nfz-guaranteed#1.6.1.1 "morfologia krwi obwodowej z płytkami krwi"
* $nfz-guaranteed#1.6.1.2 "morfologia krwi obwodowej z wzorem odsetkowym i płytkami krwi"
* $nfz-guaranteed#5.1.1.13 "odczyn opadania krwinek czerwonych (OB)"
* $nfz-guaranteed#1.6.1.4 "odczyn opadania krwinek czerwonych (OB)"
* $nfz-guaranteed#1.6.3.1 "ogólne badanie moczu z oceną właściwości fizycznych chemicznych oraz oceną mikroskopową osadu"
* $nfz-guaranteed#1.6.4.2 "pasożyty"
* $nfz-guaranteed#1.6.6.3 "posiew kału w kierunku pałeczek Salmonella i Shigella"
* $nfz-guaranteed#1.6.6.1 "posiew moczu z antybiogramem"
* $nfz-guaranteed#1.6.6.2 "posiew wymazu z gardła z antybiogramem"
* $nfz-guaranteed#5.1.1.4 "potas (K)"
* $nfz-guaranteed#1.6.2.2 "potas"
* $nfz-guaranteed#1.3a.1.3 "poziom kreatyniny we krwi wraz z oszacowaną wartością eGFR)"
* $nfz-guaranteed#1.6.2.13 "proteinogram"
* $nfz-guaranteed#1.6a.1.6 "przeciwciała anty-HCV"
* $nfz-guaranteed#1.6.2.37 "PSA ‒ Antygen swoisty dla stercza całkowity"
* $nfz-guaranteed#1.3a.2.4 "PSA całkowity u mężczyzn"
* $nfz-guaranteed#1.6.1.3 "retikulocyty"
* $nfz-guaranteed#5.1.1.5 "sód (Na)"
* $nfz-guaranteed#1.6.2.1 "sód"
* $nfz-guaranteed#1.3a.1.2 "stężenie glukozy we krwi"
* $nfz-guaranteed#1.6.2.7 "stężenie hemoglobiny glikowanej (HbAlc)"
* $nfz-guaranteed#1.3a.2.6 "stężenie lipoproteiny (a) we krwi – wykonywaną w ramach Bilansu raz w życiu między 20 a 40 rokiem życia"
* $nfz-guaranteed#1.6.2.6 "stężenie transferyny"
* $nfz-guaranteed#1.6.2.38 "stężenie wapnia całkowitego w surowicy krwi"
* $nfz-guaranteed#1.6.6.4 "test antygenowy SARS-CoV-2 uzyskiwany za pomocą Systemu Dystrybucji Szczepionek (SDS)"
* $nfz-guaranteed#5.1.1.12 "test antygenowy w kierunku: SARS CoV-2 / grypy A+B / RSV"
* $nfz-guaranteed#1.6.6.5 "test antygenowy w kierunku: SARS-CoV-2/grypy A+B/RSV"
* $nfz-guaranteed#1.3a.2.7 "Test na krew utajoną w kale metodą immunochemiczną (FIT-OC) - dla osób powyżej 50 roku życia"
* $nfz-guaranteed#1.6.2.11 "test obciążenia glukozą"
* $nfz-guaranteed#1.4.1.4 "triglicerydy"
* $nfz-guaranteed#1.6.2.20 "triglicerydy (TG)"
* $nfz-guaranteed#7.2.2.b "UACR (wskaźnik albumina/kreatynina w moczu)"
* $nfz-guaranteed#7.1.2.i "UACR (wskaźnik albumina/kreatynina w moczu)"
* $nfz-guaranteed#1.6.2.34 "VDRL"
* $nfz-guaranteed#1.6.2.3 "wapń zjonizowany"
* $nfz-guaranteed#5.1.1.18 "wapń zjonizowany"
* $nfz-guaranteed#1.6a.1.2 "witamina B12 "
* $nfz-guaranteed#1.6.5.1 "wskaźnik protrombinowy (INR)"
* $nfz-guaranteed#5.1.1.14 "wskaźnik protrombinowy (INR)"
* $nfz-guaranteed#1.6.2.5 "żelazo ‒ całkowita zdolność wiązania (TIBC)"
* $nfz-guaranteed#1.6.2.4 "żelazo"

