ValueSet: SsidlIcd9PlServiceCodeVS
Id: ssidl-icd9plServiceCode-VS
Title: "Kody usług laboratoryjnych ICD-9 PL"
Description: "Kody usług laboratoryjnych wybrane do propjektu SSIDL wyrażone za pomocą słownika ICD9-PL"
* $icd-9-pl#L08 "Fibronektyna"
* $icd-9-pl#C53 "Morfologia krwi 8-parametrowa"
* $icd-9-pl#C30 "Leukocyty – liczba"
* $icd-9-pl#C02 "Erytrocyty – liczba"
* $icd-9-pl#C55 "Morfologia krwi, z pełnym różnicowaniem granulocytów"
* $icd-9-pl#C09 "Erytrogram"
* $icd-9-pl#C66 "Płytki krwi – liczba"
* $icd-9-pl#C69 "Retykulocyty"
* $icd-9-pl#I81 "Białko C-reaktywne (CRP)"
* $icd-9-pl#I17 "Aminotransferaza alaninowa (ALT)"
* $icd-9-pl#K21 "Czynnik reumatoidalny (RF)"
* $icd-9-pl#L91 "Immunoglobuliny E swoiste (IgE)"
* $icd-9-pl#U75 "Streptococcus pyogenes Gr. A Przeciwciała (Antystreptolizyna O)"
* $icd-9-pl#L89 "Immunoglobuliny E całkowite (IgE)"
* $icd-9-pl#O83 "Witamina B12"
* $icd-9-pl#C59 "Odczyn opadania krwinek czerwonych"
* $icd-9-pl#M41 "Kwas foliowy"
* $icd-9-pl#L69 "Hormon tyreotropowy (TSH)"
* $icd-9-pl#O55 "Trijodotyronina wolna (FT3)"
* $icd-9-pl#O69 "Tyroksyna wolna (FT4)"
* $icd-9-pl#I61 "Antygen swoisty dla stercza (PSA) całkowity"
* $icd-9-pl#N66 "Przeciwciała przeciw białkom bogatym w cytrulinę (CCP)"
* $icd-9-pl#I19 "Aminotransferaza asparaginianowa (AST)"
* $icd-9-pl#I79 "Białko całkowite, rozdział elektroforetyczny"
* $icd-9-pl#M19 "Kinaza fosfokreatynowa izoenzym CK-MB (CKMB)"
* $icd-9-pl#N24 "NT-proBNP"
* $icd-9-pl#O09 "Przeciwciała przeciw peroksydazie tarczycowej"
* $icd-9-pl#O18 "Przeciwciała przeciw tyreoglobulinie"
* $icd-9-pl#O15 "Przeciwciała przeciw receptorowi tyreotropiny"
* $icd-9-pl#F38 "Wirus brodawczaka ludzkiego (HPV) HPV-DNA"
* $icd-9-pl#L31 "Gamma glutamylotranspeptydaza (GGTP)"
* $icd-9-pl#M18 "Kinaza fosfokreatynowa (CK)"
* $icd-9-pl#L07 "α-fetoproteina (AFP)"
* $icd-9-pl#A23 "Resztki pokarmowe w kale"
* $icd-9-pl#L11 "Fosfataza alkaliczna"
* $icd-9-pl#N13 "Mocznik"
* $icd-9-pl#L15 "Fosfataza kwaśna całkowita"
* $icd-9-pl#I89 "Bilirubina całkowita"
* $icd-9-pl#I87 "Bilirubina bezpośrednia"
* $icd-9-pl#X01 "Ascaris lumbricoides Przeciwciała IgG (anty-Ascaris lumbricoides)"
* $icd-9-pl#X49 "Toxoplasma gondii Awidność Przeciwciała IgG (anty-T. gondii)"
* $icd-9-pl#X13 "Giardia lamblia Antygen (Giardia lamblia Antygen)"
* $icd-9-pl#A21 "Pasożyty/ jaja pasożytów w kale"
* $icd-9-pl#M37 "Kreatynina"
* $icd-9-pl#X35 "Toxoplasma gondii Przeciwciała"
* $icd-9-pl#X45 "Toxoplasma gondii Przeciwciała IgM (anty-Toxolpasma gondii IgM)"
* $icd-9-pl#X41 "Toxoplasma gondii Przeciwciała IgG (anty-Toxoplasma gondii IgG)"
* $icd-9-pl#G11 "Czas częściowej tromboplastyny po aktywacji (APTT)"
* $icd-9-pl#P31 "Etylowy alkohol"
* $icd-9-pl#G21 "Czas protrombinowy (PT)"
* $icd-9-pl#G53 "Fibrynogen (FIBR)"
* $icd-9-pl#G54 "Fibrynogen (FIBR) - metodą inną niż koagulometryczna"
* $icd-9-pl#I09 "Albumina"
* $icd-9-pl#V22 "Wirus różyczki (Rubella virus) Przeciwciała"
* $icd-9-pl#V23 "Wirus różyczki (Rubella virus) IgM (anty-Rubella virus IgM)"
* $icd-9-pl#V19 "Wirus różyczki (Rubella virus) Przeciwciała IgG (anty-Rubella virus IgG)"
* $icd-9-pl#V21 "Wirus różyczki (Rubella virus) Przeciwciała IgG (anty-Rubella virus IgG) (ilościowo)"
* $icd-9-pl#F23 "Cytomegalovirus (CMV) Przeciwciała IgM (anty-Cytomegalovirus IgM)"
* $icd-9-pl#F19 "Cytomegalovirus (CMV) Przeciwciała IgG (anty-Cytomegalovirus IgG)"
* $icd-9-pl#I25 "Amylaza"
* $icd-9-pl#I77 "Białko całkowite"
* $icd-9-pl#L43 "Glukoza z krwi żylnej"
* $icd-9-pl#I99 "Cholesterol całkowity"
* $icd-9-pl#O35 "Sód (Na)"
* $icd-9-pl#N45 "Potas (K)"
* $icd-9-pl#I97 "Chlorek(Cl)"
* $icd-9-pl#O75 "Wapń zjonizowany (Ca2+)"
* $icd-9-pl#O77 "Wapń całkowity (Ca)"
* $icd-9-pl#A07 "Białko w moczu"
* $icd-9-pl#K01 "Cholesterol HDL"
* $icd-9-pl#K03 "Cholesterol LDL"
* $icd-9-pl#M45 "Kwas moczowy"
* $icd-9-pl#G33 "Czynnik krzepnięcia VIII (FVIII)"
* $icd-9-pl#A17 "Krew utajona w kale"
* $icd-9-pl#F87 "Wirus/ przeciwciała nabytego niedoboru odporności (HIV) Antygen p24"
* $icd-9-pl#F91 "Wirus/ przeciwciała nabytego niedoboru odporności (HIV) Antygen/ Przeciwciała"
* $icd-9-pl#I23 "Amoniak"
* $icd-9-pl#V48 "Wirus zapalenia wątroby typu C (HCV) Przeciwciała (anty-HCV)"
* $icd-9-pl#V39 "Wirus zapalenia wątroby typu B HBs Antygen"
* $icd-9-pl#V41 "Wirus zapalenia wątroby typu B HBs Antygen (potwierdzajacy)"
* $icd-9-pl#O93 "Żelazo - całkowita zdolność wiązania (TIBC)"
* $icd-9-pl#O95 "Żelazo (Fe)"
* $icd-9-pl#O49 "Triglicerydy"
* $icd-9-pl#A15 "Glukoza w moczu"
* $icd-9-pl#O43 "Transferyna"
* $icd-9-pl#L05 "Ferrytyna"
* $icd-9-pl#V100 "Wirus SARS-CoV-2 Antygen"
* $icd-9-pl#M69 "Lipoproteina a [Lp(a)]"
* $icd-9-pl#U15 "Helicobacter pylori Antygen"
* $icd-9-pl#L55 "Hemoglobina glikowana (HbA1c)"
* $icd-9-pl#V101 "Wirus grypy typu A i B/ SARS-CoV-2/ RS Antygen"
* $icd-9-pl#F78 "Wirus Influenza B Antygen"
* $icd-9-pl#F73 "Wirus Influenza A Antygen"
* $icd-9-pl#C43 "Limfocyty TCD4+"
* $icd-9-pl#C45 "Limfocyty TCD8+"
