ValueSet: SsidlMaterialTypeVS
Id: ssidl-materialType-VS
Title: "Kody materiału pobieranego do badania (SSIDL)"
Description: "Kody materiału pobieranego do badania używane w bazie wiedzy SSIDL wyrażone za pomocą pozycji słownika LOINC Part typu System lub słownika własnego SSIDL"
* $loinc-part#LP7057-5 "krew"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "8"
* $loinc-part#LP7567-3 "surowica"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "12"
* $loinc-part#LP7479-1 "osocze"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "13"
* $loinc-part#LP7576-4 "surowica lub osocze"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "14"
* $loinc-part#LP7681-2 "mocz"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "15"
* $loinc-part#LP7156-5 "płyn mózgowo-rdzeniowy"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "16"
* $loinc-part#LP7604-4 "kał"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "17"
* $loinc-part#LP7061-7 "krew lub tkanka"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "31"
* $loinc-part#LP185743-4 "płyn owodniowy lub próbka kosmówki"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "32"
* $loinc-part#LP7370-2 "izolat"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "34"
* $loinc-part#LP7162-3 "szyjka macicy"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "35"
* $loinc-part#LP7633-3 "gardło"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "36"
* $loinc-part#LP7443-7 "nos"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "37"
* $loinc-part#LP7006-2 "odbyt"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "38"
* $loinc-part#LP157726-3 "wydzieliny z pochwy+odbytnicy"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "39"
* $loinc-part#LP7091-4 "wydzielina oskrzelowa"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "41"
* $loinc-part#LP438103-6 "Próbka z układu oddechowego.górna część"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "42"
* $loinc-part#LP436142-6 "Próbka z układu oddechowego"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "43"
* $loinc-part#LP30875-6 "nosogardziel"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "44"
* $loinc-part#LP7494-0 "osocze ubogopłytkowe"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "45"
* $loinc-part#LP7536-8 "krwinki czerwone"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "46"
* $loinc-part#LP234795-5 "Izolat.infekcja dróg moczowych"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "47"
* $loinc-part#LP7000-5 "płyn owodniowy"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "27"
* $loinc-part#LP183539-8 "krew - dodatni posiew"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "40"
