ValueSet: SsidlLoincConceptVS
Id: ssidl-loincConcept-VS
Title: "Kody LOINC usług w projekcie SSIDL"
Description: "Kody LOINC usług laboratoryjnych wybranych do projektu SSIDL"
// SSIDL LOINC Concept code and Polish FSN
* $loinc#10704-5 "Ova and parasites identified in Stool by Light microscopy"
* $loinc#1670-9 "17-Hydroxyprogesterone [Mass/volume] in Urine"
* $loinc#14570-6 "17-Hydroxyprogesterone [Moles/volume] in Urine"
* $loinc#1715-2 "Acid phosphatase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#13590-5  "Activated protein C resistance [Time Ratio] in Platelet poor plasma by Coagulation assay"
* $loinc#48596-1 "Activated protein C resistance panel - Platelet poor plasma LHC-Forms"
* $loinc#3209-4 "Aktywność czynnika krzepnięcia VIII badane/prawidłowe:względna jednostka czasu:punkt w czasie:osocze ubogopłytkowe:ilościowy:test krzepnięcia"
* $loinc#2862-1 "Albumin [Mass/volume] in Serum or Plasma by Electrophoresis"
* $loinc#14585-4 "Albumin/Creatinine [Molar ratio] in Urine"
* $loinc#1759-0 "Albumin/Globulin [Mass Ratio] in Serum or Plasma"
* $loinc#13980-8 "Albumin/Protein.total in Serum or Plasma by Electrophoresis"
* $loinc#9318-7 "Albumina/kreatynina:współczynnik masowy:punkt w czasie:mocz:ilościowy:"
* $loinc#32294-1 "Albumina/kreatynina:współczynnik:punkt w czasie:mocz:ilościowy:"
* $loinc#1754-1 "Albumina:stężenie masowe:punkt w czasie:mocz:ilościowy:"
* $loinc#1751-7 "Albumina:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#61152-5 "Albumina:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:metoda wiązania czerwieni bromokrezolowej (BCP)"
* $loinc#61151-7 "Albumina:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:metoda wiązania zieleni bromokrezolowej (BCG)"
* $loinc#6019-4 "Almond IgE Ab [Units/volume] in Serum"
* $loinc#2865-4 "Alpha 1 globulin [Mass/volume] in Serum or Plasma by Electrophoresis"
* $loinc#13978-2 "Alpha 1 globulin/Protein.total in Serum or Plasma by Electrophoresis"
* $loinc#2868-8 "Alpha 2 globulin [Mass/volume] in Serum or Plasma by Electrophoresis"
* $loinc#13981-6 "Alpha 2 globulin/Protein.total in Serum or Plasma by Electrophoresis"
* $loinc#1834-1 "Alpha-1-Fetoprotein [Mass/volume] in Serum or Plasma"
* $loinc#83073-7 "Alpha-1-Fetoprotein [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#83073-7  "Alpha-1-Fetoprotein [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#19177-5 "Alpha-1-Fetoprotein [Moles/volume] in Serum or Plasma"
* $loinc#19176-7 "Alpha-1-Fetoprotein [Units/volume] in Serum or Plasma"
* $loinc#83072-9 "Alpha-1-Fetoprotein [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#53962-7 "Alpha-1-fetoprotein.tumor marker [Mass/volume] in Serum or Plasma"
* $loinc#53960-1 "Alpha-1-fetoprotein.tumor marker [Moles/volume] in Serum or Plasma"
* $loinc#53961-9 "Alpha-1-fetoprotein.tumor marker [Units/volume] in Serum or Plasma"
* $loinc#6020-2 "Alternaria alternata IgE Ab [Units/volume] in Serum"
* $loinc#6020-2 "Alternaria alternata IgE Ab [Units/volume] in Serum"
* $loinc#6095-4 "American house dust mite IgE Ab [Units/volume] in Serum"
* $loinc#1742-6 "Aminotransferaza alaninowa:stężenie katalityczne:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#1744-2 "Aminotransferaza alaninowa:stężenie katalityczne:punkt w czasie:surowica lub osocze:ilościowy:bez dodatku P-5'-P"
* $loinc#1743-4 "Aminotransferaza alaninowa:stężenie katalityczne:punkt w czasie:surowica lub osocze:ilościowy:z fosforanem pirydoksalu P-5'-P"
* $loinc#77144-4 "Aminotransferaza alaninowa:stężenie katalityczne:punkt w czasie:surowica, osocze lub krew:ilościowy:"
* $loinc#22763-7  "Ammonia [Mass/volume] in Plasma"
* $loinc#16362-6 "Ammonia [Moles/volume] in Plasma"
* $loinc#25144-7 "Ammonium urate crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5766-1 "Ammonium urate crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#8246-1 "Amorphous sediment [Presence] in Urine sediment by Light microscopy"
* $loinc#17-4 "Amoxicillin [Susceptibility] by Disk diffusion (KB)"
* $loinc#16-6 "Amoxicillin [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#21-6 "Amoxicillin+Clavulanate [Susceptibility] by Disk diffusion (KB)"
* $loinc#20-8 "Amoxicillin+Clavulanate [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#103672-2  "Amoxicillin+Clavulanate [Susceptibility] for UTI"
* $loinc#55616-7 "Amoxicillin+Sulbactam [Susceptibility] by Disk diffusion (KB)"
* $loinc#29-9  "Ampicillin [Susceptibility] by Disk diffusion (KB)"
* $loinc#28-1 "Ampicillin [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#1798-8 "Amylase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#1799-6 "Amylase [Enzymatic activity/volume] in Urine"
* $loinc#68467-0 "APOB+LDLR+PCSK9 gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal"
* $loinc#5767-9 "Appearance of Urine"
* $loinc#6021-0  "Apple IgE Ab [Units/volume] in Serum"
* $loinc#6021-0 "Apple IgE Ab [Units/volume] in Serum"
* $loinc#42578-5 "Artifact [Presence] in Urine sediment by Light microscopy"
* $loinc#40607-4 "Ascaris lumbricoides IgG Ab [Units/volume] in Serum by Immunoassay"
* $loinc#1920-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#88112-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma by No addition of P-5'-P"
* $loinc#30239-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma by With P-5'-P"
* $loinc#17899-6 "Bacteria # 2 identified in Throat by Aerobe culture"
* $loinc#17970-5 "Bacteria # 2 identified in Urine by Culture"
* $loinc#17900-2 "Bacteria # 3 identified in Throat by Aerobe culture"
* $loinc#17971-3 "Bacteria # 3 identified in Urine by Culture"
* $loinc#17901-0 "Bacteria # 4 identified in Throat by Aerobe culture"
* $loinc#5769-5 "Bacteria [#/area] in Urine sediment by Microscopy high power field"
* $loinc#25145-4 "Bacteria [Presence] in Urine sediment by Light microscopy"
* $loinc#105900-5 "Bacteria Identification [Presence] in Isolate"
* $loinc#105900-5 "Bacteria Identification [Presence] in Isolate"
* $loinc#105900-5 "Bacteria Identification [Presence] in Isolate"
* $loinc#105900-5 "Bacteria Identification [Presence] in Isolate"
* $loinc#105900-5 "Bacteria Identification [Presence] in Isolate"
* $loinc#13315-7 "Bacteria identified in 24 hour Urine by Culture"
* $loinc#17928-3 "Bacteria identified in Blood by Aerobe culture"
* $loinc#17934-1 "Bacteria identified in Blood by Anaerobe culture"
* $loinc#604-9  "Bacteria identified in Bronchial specimen by Aerobe culture"
* $loinc#17898-8 "Bacteria identified in Throat by Aerobe culture"
* $loinc#626-2 "Bacteria identified in Throat by Culture"
* $loinc#630-4 "Bacteria identified in Urine by Culture"
* $loinc#29576-6 "Bacterial susceptibility panel"
* $loinc#29576-6 "Bacterial susceptibility panel"
* $loinc#29576-6 "Bacterial susceptibility panel"
* $loinc#29576-6 "Bacterial susceptibility panel"
* $loinc#29576-6 "Bacterial susceptibility panel"
* $loinc#94087-4  "Badanie chromosomów:wynik:punkt w czasie:krew lub tkanka:dokument:mikromacierz"
* $loinc#704-7 "Bazofile [#/objętość]"
* $loinc#706-2  "Bazofile [%]"
* $loinc#32730-4 "Beta 1 globulin [Mass/volume] in Serum or Plasma by Electrophoresis"
* $loinc#32732-0 "Beta 1 globulin/Protein.total in Serum or Plasma by Electrophoresis"
* $loinc#32731-2 "Beta 2 globulin [Mass/volume] in Serum or Plasma by Electrophoresis"
* $loinc#32733-8 "Beta 2 globulin/Protein.total in Serum or Plasma by Electrophoresis"
* $loinc#2887-8 "Białko:granica wykrywalności:punkt w czasie:mocz:półilościowy:"
* $loinc#20454-5 "Białko:granica wykrywalności:punkt w czasie:mocz:półilościowy:test paskowy"
* $loinc#57735-3 "Białko:granica wykrywalności:punkt w czasie:mocz:półilościowy:test paskowy automatyczny"
* $loinc#35663-4 "Białko:stężenie masowe:nieokreślony:mocz:ilościowy:"
* $loinc#2888-6 "Białko:stężenie masowe:punkt w czasie:mocz:ilościowy:"
* $loinc#5804-0 "Białko:stężenie masowe:punkt w czasie:mocz:półilościowy:test paskowy"
* $loinc#50561-0 "Białko:stężenie masowe:punkt w czasie:mocz:półilościowy:test paskowy automatyczny"
* $loinc#2885-2 "Białko:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#58450-8 "Bilirubin [Presence] in Urine by Confirmatory method"
* $loinc#25146-2 "Bilirubin crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5771-1 "Bilirubin crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#20505-4 "Bilirubin.total [Mass/volume] in Urine by Test strip"
* $loinc#5770-3 "Bilirubin.total [Presence] in Urine by Test strip"
* $loinc#1968-7 "Bilirubina, glukuronidowana+bilirubina, związana z albuminą:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#14629-0 "Bilirubina, glukuronidowana+bilirubina, związana z albuminą:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#1975-2 "Bilirubina:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#14631-6 "Bilirubina:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#77137-8 "Bilirubina:stężenie molowe:punkt w czasie:surowica, osocze lub krew:ilościowy:"
* $loinc#75217-0  "Biotinidase [Enzymatic activity/volume] in DBS"
* $loinc#11278-9 "Bladder cells [#/area] in Urine sediment by Microscopy high power field"
* $loinc#1988-5 "C reactive protein [Mass/volume] in Serum or Plasma"
* $loinc#30522-7 "C reactive protein [Mass/volume] in Serum or Plasma by High sensitivity method"
* $loinc#106736-2 "C reactive protein [Mass/volume] in Serum, Plasma or Blood by Rapid immunoassay"
* $loinc#76485-2 "C reactive protein [Moles/volume] in Serum or Plasma"
* $loinc#76486-0 "C reactive protein [Moles/volume] in Serum or Plasma by High sensitivity method"
* $loinc#25148-8 "Calcium oxalate crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5774-5 "Calcium oxalate crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#25149-6 "Calcium phosphate crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5775-2 "Calcium phosphate crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#12180-6 "Calcium.ionized [Moles/volume] in Serum or Plasma by Ion-selective membrane electrode (ISE)"
* $loinc#38445-3 "Calprotectin [Mass/mass] in Stool"
* $loinc#6061-6 "Carrot IgE Ab [Units/volume] in Serum"
* $loinc#6061-6 "Carrot IgE Ab [Units/volume] in Serum"
* $loinc#6062-4 "Casein IgE Ab [Units/volume] in Serum"
* $loinc#24124-0 "Casts [Presence] in Urine sediment by Light microscopy"
* $loinc#58436-7 "Casts [Type] in Urine sediment by Light microscopy"
* $loinc#6833-8 "Cat dander IgE Ab [Units/volume] in Serum"
* $loinc#6833-8 "Cat dander IgE Ab [Units/volume] in Serum"
* $loinc#58410-2 "CBC panel - Blood by Automated count"
* $loinc#57021-8 "CBC W Auto Differential panel - Blood"
* $loinc#54218-3 "CD3+CD4+ (T4 helper) cells/CD3+CD8+ (T8 suppressor cells) cells [# Ratio] in Blood"
* $loinc#65-3 "Cefadroxil [Susceptibility] by Disk diffusion (KB)"
* $loinc#64-6 "Cefadroxil [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#109-9 "Cefotaxime [Susceptibility] by Disk diffusion (KB)"
* $loinc#108-1 "Cefotaxime [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#142-0 "cefTRIAXone [Susceptibility] by Disk diffusion (KB)"
* $loinc#141-2 "cefTRIAXone [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#35782-2 "Cefuroxime Oral [Susceptibility] by Disk diffusion (KB)"
* $loinc#20460-2 "Cefuroxime Oral [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#146-1 "Cefuroxime Parenteral [Susceptibility] by Disk diffusion (KB)"
* $loinc#145-3 "Cefuroxime Parenteral [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#6065-7 "Celery IgE Ab [Units/volume] in Serum"
* $loinc#58438-3 "Cells [Type] in Urine sediment by Light microscopy"
* $loinc#150-3 "Cephalexin [Susceptibility] by Disk diffusion (KB)"
* $loinc#149-5 "Cephalexin [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#21655-6 "CFTR gene.p.Phe508del [Presence] in Blood or Tissue by Molecular genetics method"
* $loinc#2075-0 "Chlorek:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#25153-8 "Cholesterol crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5777-8 "Cholesterol crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#2085-9 "Cholesterol w HDL:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#14646-4 "Cholesterol w HDL:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#2089-1 "Cholesterol w LDL:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#13457-7 "Cholesterol w LDL:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:obliczony"
* $loinc#18262-6 "Cholesterol w LDL:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:test bezpośredni"
* $loinc#22748-8 "Cholesterol w LDL:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#39469-2 "Cholesterol w LDL:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:obliczony"
* $loinc#69419-0 "Cholesterol w LDL:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:test bezpośredni"
* $loinc#2093-3 "Cholesterol:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#14647-2 "Cholesterol:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#57317-0 "Chromosome 13+18+21+X+Y aneuploidy in Amniotic fluid or Chorionic villus sample by FISH Nominal"
* $loinc#186-7 "Ciprofloxacin [Susceptibility] by Disk diffusion (KB)"
* $loinc#185-9 "Ciprofloxacin [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#32167-9 "Clarity of Urine"
* $loinc#33393-0 "Coarse Granular Casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#32175-2 "Coarse Granular Casts [Presence] in Urine sediment by Light microscopy"
* $loinc#2132-9 "Cobalamin (Vitamin B12) [Mass/volume] in Serum or Plasma"
* $loinc#14685-2 "Cobalamin (Vitamin B12) [Moles/volume] in Serum or Plasma"
* $loinc#6195-2 "Cocksfoot IgE Ab [Units/volume] in Serum"
* $loinc#6082-2 "Codfish IgE Ab [Units/volume] in Serum"
* $loinc#564-5 "Colony count [#] in Specimen by Visual count"
* $loinc#19091-8 "Colony count [#] in Urine by Visual count"
* $loinc#9397-1 "Color of Stool"
* $loinc#5778-6 "Color of Urine"
* $loinc#11029-6 "Consistency of Stool"
* $loinc#51662-5 "Core respiratory allergens panel - Serum"
* $loinc#7258-7 "Cow milk IgE Ab [Units/volume] in Serum"
* $loinc#6092-1 "Crab IgE Ab [Units/volume] in Serum"
* $loinc#32673-6 "Creatine kinase.MB [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#13969-1 "Creatine kinase.MB [Mass/volume] in Serum or Plasma"
* $loinc#83092-7 "Creatine kinase.MB [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#101446-3 "Creatine kinase.MB [Moles/volume] in Serum or Plasma by Immunoassay"
* $loinc#49755-2 "Crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#5782-8 "Crystals [type] in Urine sediment by Light microscopy"
* $loinc#6236-4 "Cultivated Rye IgE Ab [Units/volume] in Serum"
* $loinc#6236-4 "Cultivated Rye IgE Ab [Units/volume] in Serum"
* $loinc#53027-9 "Cyclic citrullinated peptide Ab [Units/volume] in Serum"
* $loinc#32218-0 "Cyclic citrullinated peptide Ab [Units/volume] in Serum by Immunoassay"
* $loinc#25155-3 "Cystine crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5784-4 "Cystine crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#5124-3 "Cytomegalovirus IgG Ab [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#5126-8 "Cytomegalovirus IgM Ab [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#14979-9 "Czas częściowej tromboplastyny po aktywacji:czas:punkt w czasie:osocze ubogopłytkowe:ilościowy:test krzepnięcia"
* $loinc#75383-0 "DMD gene deletion and duplication mutation analysis in Amniotic fluid or Chorionic villus sample by MLPA"
* $loinc#75385-5 "DMD gene deletion and duplication mutation analysis in Blood or Tissue by MLPA"
* $loinc#21247-2 "DMD gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal"
* $loinc#22075-6 "DMD gene mutations tested for in Blood or Tissue by Molecular genetics method Nominal"
* $loinc#50626-1 "DMD gene targeted mutation analysis in Blood or Tissue by Molecular genetics method"
* $loinc#6098-8 "Dog dander IgE Ab [Units/volume] in Serum"
* $loinc#6098-8 "Dog dander IgE Ab [Units/volume] in Serum"
* $loinc#53975-9 "Drug crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#6106-9 "Egg white IgE Ab [Units/volume] in Serum"
* $loinc#6107-7 "Egg yolk IgE Ab [Units/volume] in Serum"
* $loinc#6110-1 "English plantain IgE Ab [Units/volume] in Serum"
* $loinc#100900-0 "Enterobacteriaceae.carbapenem resistance panel - Anal by Organism specific culture"
* $loinc#100901-8 "Enterobacteriaceae.carbapenemase resistance phenotype [Identifier] in Anal by Organism specific culture"
* $loinc#100902-6 "Enterobacteriaceae.carbapenemase resistance phenotype.OXA-48 [Identifier] in Anal by Organism specific culture"
* $loinc#6676-1 "Enterobius vermicularis [Presence] in Anal by Pinworm exam"
* $loinc#77345-7 "Enterobius vermicularis [Presence] in Anal by Pinworm exam --2nd specimen"
* $loinc#77346-5 "Enterobius vermicularis [Presence] in Anal by Pinworm exam --3rd specimen"
* $loinc#45379-5 "Eosinophils [Presence] in Stool by Light microscopy"
* $loinc#711-2 "Eozynofile [#/objętość]"
* $loinc#713-8  "Eozynofile [%]"
* $loinc#5786-9 "Epithelial casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#25157-9 "Epithelial casts [Presence] in Urine sediment by Light microscopy"
* $loinc#5787-7 "Epithelial cells [#/area] in Urine sediment by Microscopy high power field"
* $loinc#14103-6 "Epithelial cells [Presence] in Stool by Light microscopy"
* $loinc#20453-7 "Epithelial cells [Presence] in Urine sediment by Light microscopy"
* $loinc#26051-3 "Epithelial cells.extrarenal [#/area] in Urine sediment by Microscopy high power field"
* $loinc#53978-3 "Epithelial cells.non-squamous [Presence] in Urine sediment by Light microscopy"
* $loinc#26052-1 "Epithelial cells.renal [#/area] in Urine sediment by Microscopy high power field"
* $loinc#12248-1 "Epithelial cells.renal [Presence] in Urine sediment by Light microscopy"
* $loinc#11277-1 "Epithelial cells.squamous [#/area] in Urine sediment by Microscopy high power field"
* $loinc#12258-0 "Epithelial cells.squamous [Presence] in Urine sediment by Light microscopy"
* $loinc#13945-1 "Erythrocytes [#/area] in Urine sediment by Microscopy high power field"
* $loinc#32776-7 "Erythrocytes [Presence] in Urine sediment by Light microscopy"
* $loinc#58444-1 "Erythrocytes.dysmorphic [Presence] in Urine sediment by Light microscopy"
* $loinc#789-8 "Erytrocyty [#/objętość]"
* $loinc#771-6 "Erytrocyty jądrzaste [#/objętość]"
* $loinc#58413-6 "Erytrocyty jądrzaste NRBC [%]"
* $loinc#5640-8 "Ethanol [Mass/volume] in Blood"
* $loinc#56478-1 "Ethanol [Mass/volume] in Blood by Gas chromatography"
* $loinc#74859-0 "Ethanol [Mass/volume] in Blood Estimated from serum or plasma level"
* $loinc#5643-2 "Ethanol [Mass/volume] in Serum or Plasma"
* $loinc#14336-2 "Ethanol [Mass/volume] in Serum or Plasma by Gas chromatography"
* $loinc#15120-9 "Ethanol [Moles/volume] in Blood"
* $loinc#14719-9 "Ethanol [Moles/volume] in Serum or Plasma"
* $loinc#6096-2 "European house dust mite IgE Ab [Units/volume] in Serum"
* $loinc#6096-2 "European house dust mite IgE Ab [Units/volume] in Serum"
* $loinc#24475-6 "F2 gene c.20210G>A [Genotype] in Blood or Tissue by Molecular genetics method Nominal"
* $loinc#21668-9 "F5 gene p.Arg506Gln [Presence] in Blood or Tissue by Molecular genetics method"
* $loinc#1558-6 "Fasting glucose [Mass/volume] in Serum or Plasma"
* $loinc#14771-0 "Fasting glucose [Moles/volume] in Serum or Plasma"
* $loinc#5789-3 "Fatty casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#25159-5 "Fatty casts [Presence] in Urine sediment by Light microscopy"
* $loinc#2276-4 "Ferritin [Mass/volume] in Serum or Plasma"
* $loinc#14723-1 "Ferritin [Moles/volume] in Serum or Plasma"
* $loinc#47407-2 "Fibers [#/area] in Stool by Light microscopy"
* $loinc#38897-5 "Fibers [Presence] in Stool by Light microscopy"
* $loinc#3255-7 "Fibrinogen [Mass/volume] in Platelet poor plasma by Coagulation assay"
* $loinc#48664-7 "Fibrinogen [Mass/volume] in Platelet poor plasma by Coagulation.derived"
* $loinc#7311-4 "Fish IgE Ab [Units/volume] in Serum"
* $loinc#2284-8 "Folate [Mass/volume] in Serum or Plasma"
* $loinc#14732-2 "Folate [Moles/volume] in Serum or Plasma"
* $loinc#49222-3 "Food allergen panel - Serum"
* $loinc#6768-6 "Fosfataza zasadowa:stężenie katalityczne:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#35810-1 "Fosfomycin [Susceptibility] by Disk diffusion (KB)"
* $loinc#25653-7 "Fosfomycin [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#5790-1 "Fungi.filamentous [#/area] in Urine sediment by Microscopy high power field"
* $loinc#20457-8 "Fungi.filamentous [Presence] in Urine sediment by Light microscopy"
* $loinc#5791-9 "Fungi.yeastlike [#/area] in Urine sediment by Microscopy high power field"
* $loinc#20456-0 "Fungi.yeastlike [Presence] in Urine sediment by Light microscopy"
* $loinc#569-4  "Fungus identified in Cerebral spinal fluid by Culture"
* $loinc#40435-0 "Fungus identified in Urine by Culture"
* $loinc#49634-9 "FXN gene allele 1.GAA repeats [Entitic number] in Blood or Tissue by Molecular genetics method"
* $loinc#49635-6 "FXN gene allele 2.GAA repeats [Entitic number] in Blood or Tissue by Molecular genetics method"
* $loinc#75392-1 "FXN gene GAA repeats [Presence] in Amniotic fluid or Chorionic villus sample by Molecular genetics method"
* $loinc#2874-6 "Gamma globulin [Mass/volume] in Serum or Plasma by Electrophoresis"
* $loinc#13983-2 "Gamma globulin/Protein.total in Serum or Plasma by Electrophoresis"
* $loinc#2324-2 "Gamma glutamyl transferase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#268-3  "Gentamicin [Susceptibility] by Disk diffusion (KB)"
* $loinc#267-5 "Gentamicin [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#6412-1 "Giardia lamblia Ag [Presence] in Stool by Immunoassay"
* $loinc#98979-8 "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI 2021)/1.73 sq M"
* $loinc#62238-1 "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI)/1.73 sq M"
* $loinc#88293-6 "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI)/1.73 sq M among black population"
* $loinc#88294-4 "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI)/1.73 sq M among non black population"
* $loinc#77147-7 "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (MDRD)/1.73 sq M"
* $loinc#50384-7 "Glomerular filtration rate [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (Schwartz)/1.73 sq M"
* $loinc#1507-3 "Glucose [Mass/volume] in Serum or Plasma --1 hour post 75 g glucose PO"
* $loinc#1518-0 "Glucose [Mass/volume] in Serum or Plasma --2 hours post 75 g glucose PO"
* $loinc#51597-3 "Glucose [Moles/volume] in Serum or Plasma --1 hour post 75 g glucose PO"
* $loinc#14995-5 "Glucose [Moles/volume] in Serum or Plasma --2 hours post 75 g glucose PO"
* $loinc#25428-4 "Glukoza:granica wykrywalności:punkt w czasie:mocz:półilościowy:test paskowy"
* $loinc#50555-2 "Glukoza:granica wykrywalności:punkt w czasie:mocz:półilościowy:test paskowy automatyczny"
* $loinc#35662-6 "Glukoza:stężenie masowe:nieokreślony:mocz:ilościowy:"
* $loinc#2350-7 "Glukoza:stężenie masowe:punkt w czasie:mocz:ilościowy:"
* $loinc#5792-7 "Glukoza:stężenie masowe:punkt w czasie:mocz:półilościowy:test paskowy"
* $loinc#53328-1 "Glukoza:stężenie masowe:punkt w czasie:mocz:półilościowy:test paskowy automatyczny"
* $loinc#2345-7 "Glukoza:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#15076-3 "Glukoza:stężenie molowe:punkt w czasie:mocz:ilościowy:"
* $loinc#22705-8 "Glukoza:stężenie molowe:punkt w czasie:mocz:półilościowy:test paskowy"
* $loinc#59156-0 "Glukoza:stężenie molowe:punkt w czasie:mocz:półilościowy:test paskowy automatyczny"
* $loinc#14749-6 "Glukoza:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#5793-5 "Granular casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#25160-3 "Granular casts [Presence] in Urine sediment by Light microscopy"
* $loinc#53115-2 "Granulocyty niedojrzałe [#/objętość]"
* $loinc#71695-1 "Granulocyty niedojrzałe [%]"
* $loinc#15284-3 "Grey Alder IgE Ab [Units/volume] in Serum"
* $loinc#15284-3 "Grey Alder IgE Ab [Units/volume] in Serum"
* $loinc#41278-3 "Gross blood [Presence] of Stool Qualitative"
* $loinc#6134-1 "Guinea pig epithelium IgE Ab [Units/volume] in Serum"
* $loinc#6135-8 "Hamster epithelium IgE Ab [Units/volume] in Serum"
* $loinc#6136-6 "Hazelnut IgE Ab [Units/volume] in Serum"
* $loinc#6136-6 "Hazelnut IgE Ab [Units/volume] in Serum"
* $loinc#6137-4 "Hazelnut Pollen IgE Ab [Units/volume] in Serum"
* $loinc#6137-4 "Hazelnut Pollen IgE Ab [Units/volume] in Serum"
* $loinc#31843-6 "Helicobacter pylori Ag [Presence] in Stool"
* $loinc#17780-8 "Helicobacter pylori Ag [Presence] in Stool by Immunoassay"
* $loinc#80373-4 "Helicobacter pylori Ag [Presence] in Stool by Rapid immunoassay"
* $loinc#4544-3 "Hematokryt (HCT)"
* $loinc#5794-3 "Hemoglobin [Presence] in Urine by Test strip"
* $loinc#34174-3 "Hemoglobin casts [Presence] in Urine sediment by Light microscopy"
* $loinc#104738-0 "Hemoglobin.gastrointestinal.lower [Presence] in Stool"
* $loinc#29771‑3 "Hemoglobin.gastrointestinal.lower [Presence] in Stool by Immunoassay"
* $loinc#718-7 "Hemoglobina (HGB)"
* $loinc#71875-9 "Hemoglobina A1c/hemoglobina całkowita:frakcja masowa:punkt w czasie:krew:ilościowy:"
* $loinc#4548-4 "Hemoglobina A1c/hemoglobina całkowita:frakcja masowa:punkt w czasie:krew:ilościowy:"
* $loinc#17856-6 "Hemoglobina A1c/hemoglobina całkowita:frakcja masowa:punkt w czasie:krew:ilościowy:wysokosprawna chromatografia cieczowa"
* $loinc#59261-8 "Hemoglobina A1c/hemoglobina całkowita:frakcja molowa:punkt w czasie:krew:ilościowy:protokół IFCC"
* $loinc#2335-8 "Hemoglobina, żołądkowo-jelitowa:granica wykrywalności:punkt w czasie:kał:półilościowy:"
* $loinc#95234-1 "Hepatitis B virus surface Ag [Interpretation] in Serum or Plasma"
* $loinc#99385-7 "Hepatitis B virus surface Ag [log units/volume] in Serum or Plasma by Immunoassay"
* $loinc#5195-3 "Hepatitis B virus surface Ag [Presence] in Serum"
* $loinc#65633-0 "Hepatitis B v irus surface Ag [Presence] in Serum or Plasma by Confirmatory method"
* $loinc#5196-1 "Hepatitis B virus surface Ag [Presence] in Serum or Plasma by Immunoassay"
* $loinc#7905-3 "Hepatitis B virus surface Ag [Presence] in Serum or Plasma by Neutralization test"
* $loinc#58452-4 "Hepatitis B virus surface Ag [Units/volume] in Serum"
* $loinc#63557-3 "Hepatitis B virus surface Ag [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#70154-0 "Hepatitis B virus surface Ag in Serum or Plasma by Confirmatory method"
* $loinc#25161-1 "Hippurate crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5795-0 "Hippurate crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#56888-1 "HIV 1+2 Ab+HIV1 p24 Ag [Presence] in Serum or Plasma by Immunoassay"
* $loinc#6143-2 "Horse dander IgE Ab [Units/volume] in Serum"
* $loinc#104766-1 "Human papilloma virus 16+18+31+33+35+39+45+51+52+56+58+59+66+68 DNA [Presence] in Cervix by Molecular genetics method"
* $loinc#104752-1  "Human papilloma virus 16+18+31+33+35+39+45+51+52+56+58+59+68 DNA [Presence] in Cervix by Molecular genetics method"
* $loinc#5796-8 "Hyaline casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#25162-9 "Hyaline casts [Presence] in Urine sediment by Light microscopy"
* $loinc#76488-6 "IgE:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:metoda immunologiczna"
* $loinc#19113-0 "IgE:stężenie w jednostkach umownych:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#83102-4 "IgE:stężenie w jednostkach umownych:punkt w czasie:surowica lub osocze:ilościowy:metoda immunologiczna"
* $loinc#97099-6 "Influenza virus A and B and SARS-CoV-2 (COVID-19) Ag panel - Upper respiratory specimen by Rapid immunoassay"
* $loinc#6301-6 "INR in Platelet poor plasma by Coagulation assay"
* $loinc#33773-3 "Karyotype [Identifier] in Amniotic fluid Nominal"
* $loinc#50619-6 "Karyotype [Identifier] in Blood or Tissue Narrative)"
* $loinc#6153-1 "Kentucky blue grass IgE Ab [Units/volume] in Serum"
* $loinc#5797-6 "Ketones [Mass/volume] in Urine by Test strip"
* $loinc#2514-8 "Ketones [Presence] in Urine by Test strip"
* $loinc#2157-6 "Kinaza kreatynowa:stężenie katalityczne:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#11279-7 "Komentarze nt. osadu moczu:wynik:punkt w czasie:osad moczu:opisowy:mikroskopia świetlna"
* $loinc#2161-8 "Kreatynina:stężenie masowe:punkt w czasie:mocz:ilościowy:"
* $loinc#2160-0 "Kreatynina:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#14683-7 "Kreatynina:stężenie molowe:punkt w czasie:mocz:ilościowy:"
* $loinc#14682-9 "Kreatynina:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#3084-1 "Kwas moczowy:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#14933-6 "Kwas moczowy:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#56159-7 "LDLR gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal"
* $loinc#25163-7 "Leucine crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5798-4 "Leucine crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#46420-6 "Leukocyte clumps [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5799-2 "Leukocyte esterase [Presence] in Urine by Test strip"
* $loinc#5821-4 "Leukocytes [#/area] in Urine sediment by Microscopy high power field"
* $loinc#13655-6 "Leukocytes [Presence] in Stool by Light microscopy"
* $loinc#20455-2 "Leukocytes [Presence] in Urine sediment by Light microscopy"
* $loinc#6690-2 "Leukocyty [#/objętość]"
* $loinc#731-0 "Limfocyty [#/objętość]"
* $loinc#736-9 "Limfocyty [%]"
* $loinc#10835-7 "Lipoproteina (a):stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#43583-4 "Lipoproteina (a):stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#6165-5 "Lobster IgE Ab [Units/volume] in Serum"
* $loinc#38903-1 "Lymphocytes [Presence] in Stool by Light microscopy"
* $loinc#785-6 "MCH"
* $loinc#786-4 "MCHC"
* $loinc#787-2 "MCV"
* $loinc#6169-7 "Meadow Fescue IgE Ab [Units/volume] in Serum"
* $loinc#28069-3 "Meat fibers [#/area] in Stool by Light microscopy"
* $loinc#2605-4 "Meat fibers [Presence] in Stool by Light microscopy"
* $loinc#52969-3 "Methicillin resistant Staphylococcus aureus [Presence] in Nose by Organism specific cultur"
* $loinc#104553-3 "Microorganism identified by MS.MALDI-TOF in Positive blood culture"
* $loinc#104553-3 "Microorganism identified by MS.MALDI-TOF in Positive blood culture"
* $loinc#76346-6 "Microorganism identified in Isolate by MS.MALDI-TOF"
* $loinc#76346-6 "Microorganism identified in Isolate by MS.MALDI-TOF"
* $loinc#76346-6 "Microorganism identified in Isolate by MS.MALDI-TOF"
* $loinc#76346-6 "Microorganism identified in Isolate by MS.MALDI-TOF"
* $loinc#76346-6 "Microorganism identified in Isolate by MS.MALDI-TOF"
* $loinc#76346-6 "Microorganism identified in Isolate by MS.MALDI-TOF"
* $loinc#58437-5 "Microorganisms seen [Type] in Urine sediment by Light microscopy"
* $loinc#87969-2 "Microscopic observation [Identifier] in Blood by Gram stain"
* $loinc#87969-2 "Microscopic observation [Identifier] in Blood by Gram stain"
* $loinc#21021-1 "Microscopic observation [Identifier] in Bronchial specimen by Gram stain"
* $loinc#14357-8 "Microscopic observation [Identifier] in Cerebral spinal fluid by Gram stain"
* $loinc#12235-8 "Microscopic observation [Identifier] in Urine sediment by Light microscopy"
* $loinc#6174-7 "Milk IgE Ab [Units/volume] in Serum"
* $loinc#38995-7 "Mixed cellular casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#34173-5 "Mixed cellular casts [Presence] in Urine sediment by Light microscopy"
* $loinc#3091-6 "Mocznik:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#22664-7 "Mocznik:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#13348-8 "Monoclonal band observed [Identifier] in Serum or Plasma"
* $loinc#742-7 "Monocyty [#/objętość]"
* $loinc#5905-5  "Monocyty [%]"
* $loinc#32623-1  "MPV"
* $loinc#28545-2 "Mucus [#/area] in Urine sediment by Microscopy low power field"
* $loinc#42524-9 "Mucus [Presence] in Stool by Light microscopy"
* $loinc#8247-9 "Mucus [Presence] in Urine sediment by Light microscopy"
* $loinc#6183-8 "Mugwort IgE Ab [Units/volume] in Serum"
* $loinc#6183-8 "Mugwort IgE Ab [Units/volume] in Serum"
* $loinc#33762-6 "Natriuretic peptide.B prohormone N-Terminal [Mass/volume] in Serum or Plasma"
* $loinc#83107-3 "Natriuretic peptide.B prohormone N-Terminal [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#33763-4 "Natriuretic peptide.B prohormone N-Terminal [Moles/volume] in Serum or Plasma"
* $loinc#83108-1 "Natriuretic peptide.B prohormone N-Terminal [Moles/volume] in Serum or Plasma by Immunoassay"
* $loinc#751-8 "Neutrofile [#/objętość]"
* $loinc#770-8  "Neutrofile [%]"
* $loinc#43396-1 "Nie-HDL-C:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#70204-3 "Nie-HDL-C:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#5802-4 "Nitrite [Presence] in Urine by Test strip"
* $loinc#364-0  "Nitrofurantoin [Susceptibility] by Disk diffusion (KB)"
* $loinc#363-2 "Nitrofurantoin [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#54181-3  "Nitroxoline [Susceptibility] by Disk diffusion (KB)"
* $loinc#25723-8 "Nitroxoline [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#29636-8 "Obserwacja:wygląd:punkt w czasie:kał:cecha:"
* $loinc#58442-5 "Other elements [Identifier] in Urine sediment by Light microscopy"
* $loinc#10701-1 "Ova and parasites identified in Stool by Concentration"
* $loinc#18494-5 "Ova and parasites identified in Stool by Concentration--2nd specimen"
* $loinc#18493-7 "Ova and parasites identified in Stool by Concentration--3rd specimen"
* $loinc#13319-9 "Ova and parasites identified in Stool by Light microscopy--2nd specimen"
* $loinc#13320-7 "Ova and parasites identified in Stool by Light microscopy--3rd specimen"
* $loinc#20924-7 "Ova and parasites identified in Stool by Parasite sedimentation"
* $loinc#5788-5 "Oval fat bodies (globules) [#/area] in Urine sediment by Microscopy high power field"
* $loinc#25158-7 "Oval fat bodies (globules) [Presence] in Urine sediment by Light microscopy"
* $loinc#24351-9 "Panel elektroforezy białek:-:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#56158-9 "PCSK9 gene mutations found [Identifier] in Blood or Tissue by Molecular genetics method Nominal"
* $loinc#51637-7 "PCT"
* $loinc#32207-3 "PDW"
* $loinc#6205-9 "Peach IgE Ab [Units/volume] in Serum"
* $loinc#6206-7 "Peanut IgE Ab [Units/volume] in Serum"
* $loinc#6206-7 "Peanut IgE Ab [Units/volume] in Serum"
* $loinc#6207-5 "Pear IgE Ab [Units/volume] in Serum"
* $loinc#6209-1 "Pecan or Hickory Tree IgE Ab [Units/volume] in Serum"
* $loinc#6212-5 "Penicillium notatum IgE Ab [Units/volume] in Serum"
* $loinc#7369-2 "Perennial rye grass IgE Ab [Units/volume] in Serum"
* $loinc#2755-7 "pH of Stool"
* $loinc#5803-2 "pH of Urine by Test strip"
* $loinc#32145-5 "Phosphate crystals amorphous [#/area] in Urine sediment by Microscopy high power field"
* $loinc#12453-7 "Phosphate crystals amorphous [Presence] in Urine sediment by Light microscopy"
* $loinc#777-3 "Płytki krwi [#/objętość]"
* $loinc#48386-7  "Płytki olbrzymie"
* $loinc#2823-3 "Potas:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#6220-8 "Potato IgE Ab [Units/volume] in Serum"
* $loinc#2857-1 "Prostate specific Ag [Mass/volume] in Serum or Plasma"
* $loinc#35741-8 "Prostate specific Ag [Mass/volume] in Serum or Plasma by Detection limit <= 0.01 ng/mL"
* $loinc#83112-3 "Prostate specific Ag [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#19197-3 "Prostate specific Ag [Moles/volume] in Serum or Plasma"
* $loinc#19195-7 "Prostate specific Ag [Units/volume] in Serum or Plasma"
* $loinc#2885-2 "Protein [Mass/volume] in Serum or Plasma"
* $loinc#12851-2 "Protein Fractions [Interpretation] in Serum or Plasma by Electrophoresis"
* $loinc#5902-2 "Prothrombin time (PT)"
* $loinc#43422-5 "Rabbit dander IgE Ab [Units/volume] in Serum"
* $loinc#5807-3 "RBC casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#33804-6 "RBC casts [Presence] in Urine sediment by Light microscopy"
* $loinc#788-0 "RDW"
* $loinc#20507-0 "Reagin Ab [Presence] in Serum by RPR"
* $loinc#5292-8 "Reagin Ab [Presence] in Serum by VDRL"
* $loinc#31147-2 "Reagin Ab [Titer] in Serum by RPR"
* $loinc#50690-7 "Reagin Ab [Titer] in Serum by VDRL"
* $loinc#5291-0 "Reagin Ab [Units/volume] in Serum by VDRL"
* $loinc#20508-8 "Reagin Ab [Units/volume] in Serum or Plasma by RPR"
* $loinc#60474-4 "Retykulocyty:stężenie liczbowe:punkt w czasie:krew:ilościowy:automatyczne liczenie"
* $loinc#40665-2 "Retykulocyty:stężenie liczbowe:punkt w czasie:krew:ilościowy:zliczanie ręczne"
* $loinc#6928-6 "Rheumatoid factor [Units/volume] in Serum by Immunoassay"
* $loinc#11572-5 "Rheumatoid factor [Units/volume] in Serum or Plasma"
* $loinc#5334-8 "Rubella virus IgG Ab [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#5335-5 "Rubella virus IgM Ab [Units/volume] in Serum by Immunoassay"
* $loinc#7674-5 "Rye IgE Ab [Units/volume] in Serum"
* $loinc#43371-4 "Salmonella and Shigella sp identified in Stool by Organism specific culture"
* $loinc#82301-3 "Salmonella sp [Presence] in Stool by Culture"
* $loinc#94558-4 "SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory system specimen by Rapid immunoassay"
* $loinc#97097-0 "SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay"
* $loinc#6242-2 "Sesame Seed IgE Ab [Units/volume] in Serum"
* $loinc#82300-5 "Shigella sp [Presence] in Stool by Culture"
* $loinc#6246-3 "Shrimp IgE Ab [Units/volume] in Serum"
* $loinc#6246-3 "Shrimp IgE Ab [Units/volume] in Serum"
* $loinc#30984-9 "Silver Birch recombinant (rBet v) 1 IgE Ab [Units/volume] in Serum"
* $loinc#30984-9 "Silver Birch recombinant (rBet v) 1 IgE Ab [Units/volume] in Serum"
* $loinc#6248-9 "Soybean IgE Ab [Units/volume] in Serum"
* $loinc#6248-9 "Soybean IgE Ab [Units/volume] in Serum"
* $loinc#2951-2 "Sód:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#5811-5 "Specific gravity of Urine by Test strip"
* $loinc#8248-7 "Spermatozoa [Presence] in Urine sediment by Light microscopy"
* $loinc#72607-5  "Streptococcus agalactiae [Presence] in Vag+Rectum by Organism specific culture"
* $loinc#11268-0 "Streptococcus pyogenes [Presence] in Throat by Organism specific culture"
* $loinc#18481-2 "Streptococcus pyogenes Ag [Presence] in Throat"
* $loinc#546-2 "Streptococcus.beta-hemolytic [Presence] in Throat by Organism specific culture"
* $loinc#45228-4 "Streptolysin O Ab [Mass/volume] in Serum"
* $loinc#5370-2 "Streptolysin O Ab [Units/volume] in Serum or Plasma"
* $loinc#30341-2 "Szybkość opadania erytrocytów:prędkość:punkt w czasie:krew:ilościowy:"
* $loinc#82477-1 "Szybkość opadania erytrocytów:prędkość:punkt w czasie:krew:ilościowy:metoda fotometryczna"
* $loinc#4537-7 "Szybkość opadania erytrocytów:prędkość:punkt w czasie:krew:ilościowy:metoda Westergrena"
* $loinc#4538-5 "Szybkość opadania erytrocytów:prędkość:punkt w czasie:krew:ilościowy:metoda Wintrobea"
* $loinc#77039-6 "t(12;21)(p13;q22.3)(ETV6,RUNX1) fusion transcript in Blood or Tissue by FISH Badanie FISH"
* $loinc#51867-0 "t(9;22)(q34.1;q11)(ABL1,BCR) fusion transcript in Blood or Tissue by FISH Badanie FISH"
* $loinc#48804-9 "Taenia solium Ag:granica wykrywalności:punkt w czasie:kał:półilościowy:"
* $loinc#8098-6 "Thyroglobulin Ab [Units/volume] in Serum or Plasma"
* $loinc#56536-6 "Thyroglobulin Ab [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#8099-4 "Thyroperoxidase Ab [Units/volume] in Serum or Plasma"
* $loinc#56477-3 "Thyroperoxidase Ab [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#29575-8 "Thyrotropin [Units/volume] in DBS"
* $loinc#3016-3 "Thyrotropin [Units/volume] in Serum or Plasma"
* $loinc#11580-8 "Thyrotropin [Units/volume] in Serum or Plasma by Detection limit <= 0.005 mIU/L"
* $loinc#5385-0 "Thyrotropin receptor Ab [Units/volume] in Serum"
* $loinc#57416-0 "Thyrotropin receptor Ab [Units/volume] in Serum by Immunoassay"
* $loinc#3024-7 "Thyroxine (T4) free [Mass/volume] in Serum or Plasma"
* $loinc#83122-2 "Thyroxine (T4) free [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#14920-3 "Thyroxine (T4) free [Moles/volume] in Serum or Plasma"
* $loinc#83121-4 "Thyroxine (T4) free [Moles/volume] in Serum or Plasma by Immunoassay"
* $loinc#6265-3 "Timothy IgE Ab [Units/volume] in Serum"
* $loinc#6265-3 "Timothy IgE Ab [Units/volume] in Serum"
* $loinc#6266-1 "Tomato IgE Ab [Units/volume] in Serum"
* $loinc#5388-4 "Toxoplasma gondii IgG Ab [Units/volume] in Serum or Plasma by Immunoassay"
* $loinc#56990-5 "Toxoplasma gondii IgG Ab avidity [Ratio] in Serum by Immunoassay"
* $loinc#5390-0 "Toxoplasma gondii IgM Ab [Units/volume] in Serum by Immunoassay"
* $loinc#3034-6 "Transferrin [Mass/volume] in Serum or Plasma"
* $loinc#22674-6 "Transferrin [Moles/volume] in Serum or Plasma"
* $loinc#30089-7 "Transitional cells [#/area] in Urine sediment by Microscopy high power field"
* $loinc#8249-5 "Transitional cells [Presence] in Urine sediment by Light microscopy"
* $loinc#33905-1 "Trichomonas sp [#/area] in Urine sediment by Microscopy high power field"
* $loinc#32724-7 "Trichomonas sp [Presence] in Urine by Light microscopy"
* $loinc#2571-8 "Triglyceride [Mass/volume] in Serum or Plasma"
* $loinc#14927-8 "Triglyceride [Moles/volume] in Serum or Plasma"
* $loinc#3051-0 "Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma"
* $loinc#83127-1 "Triiodothyronine (T3) Free [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#14928-6 "Triiodothyronine (T3) Free [Moles/volume] in Serum or Plasma"
* $loinc#83126-3 "Triiodothyronine (T3) Free [Moles/volume] in Serum or Plasma by Immunoassay"
* $loinc#517-3 "Trimethoprim+Sulfamethoxazole [Susceptibility] by Disk diffusion (KB)"
* $loinc#516-5 "Trimethoprim+Sulfamethoxazole [Susceptibility] by Minimum inhibitory concentration (MIC)"
* $loinc#11276-3 "Tubular cells [Presence] in Urine sediment by Light microscopy"
* $loinc#53119-4 "Tyrosine crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5815-6 "Tyrosine crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#58454-0  "ubtelomere analysis [Identifier] in Blood or Tissue by Molecular genetics method Nominal Test"
* $loinc#46138-4 "Urate crystals [#/area] in Urine sediment by Microscopy high power field"
* $loinc#5817-2 "Urate crystals [Presence] in Urine sediment by Light microscopy"
* $loinc#32150-5 "Urate crystals amorphous [#/area] in Urine sediment by Microscopy high power field"
* $loinc#12454-5 "Urate crystals amorphous [Presence] in Urine sediment by Light microscopy"
* $loinc#24356-8 "Urinalysis complete panel - Urine"
* $loinc#24357-6 "Urinalysis macro (dipstick) panel - Urine"
* $loinc#50564-4 "Urinalysis panel - Urine by Automated"
* $loinc#20405-7 "Urobilinogen [Mass/volume] in Urine by Test strip"
* $loinc#2501-5 "Utajona zdolność wiązania żelaza:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#22753-8 "Utajona zdolność wiązania żelaza:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#28070-1 "Vegetable fibers [#/area] in Stool by Light microscopy"
* $loinc#55835-3 "Vegetable fibers [Presence] in Stool by Light microscopy"
* $loinc#6272-9 "Velvet grass IgE Ab [Units/volume] in Serum"
* $loinc#6273-7 "Walnut IgE Ab [Units/volume] in Serum"
* $loinc#17863-2 "Wapń, zjonizowany:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#17864-0 "Wapń, zjonizowany:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:jonoselektywne elektrody, ISE"
* $loinc#1995-0 "Wapń, zjonizowany:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#35675-8 "Wapń:stężenie masowe:nieokreślony:mocz:ilościowy:"
* $loinc#17862-4 "Wapń:stężenie masowe:punkt w czasie:mocz:ilościowy:"
* $loinc#17861-6 "Wapń:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#71790-0 "Wapń:stężenie molowe:nieokreślony:mocz:ilościowy:"
* $loinc#2004-0 "Wapń:stężenie molowe:punkt w czasie:mocz:ilościowy:"
* $loinc#2000-8 "Wapń:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#5819-8 "Waxy casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#33862-4 "Waxy casts [Presence] in Urine sediment by Light microscopy"
* $loinc#5820-6 "WBC casts [#/area] in Urine sediment by Microscopy low power field"
* $loinc#33825-1 "WBC casts [Presence] in Urine sediment by Light microscopy"
* $loinc#6276-0 "Wheat IgE Ab [Units/volume] in Serum"
* $loinc#6276-0 "Wheat IgE Ab [Units/volume] in Serum"
* $loinc#6189-5 "White Oak IgE Ab [Units/volume] in Serum"
* $loinc#7291-8 "Whole Egg IgE Ab [Units/volume] in Serum"
* $loinc#104741-4 "Wirus zapalenia wątroby typu C Ab sygnałowe/punkt odcięcia:względne stężenie umowne:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#48159-8 "Wirus zapalenia wątroby typu C Ab sygnałowe/punkt odcięcia:względne stężenie umowne:punkt w czasie:surowica lub osocze:ilościowy:metoda immunologiczna"
* $loinc#13955-0 "Wirus zapalenia wątroby typu C Ab:granica wykrywalności:punkt w czasie:surowica lub osocze:półilościowy:metoda immunologiczna"
* $loinc#16128-1 "Wirus zapalenia wątroby typu C Ab:granica wykrywalności:punkt w czasie:surowica:półilościowy:"
* $loinc#22327-1 "Wirus zapalenia wątroby typu C Ab:stężenie w jednostkach umownych:punkt w czasie:surowica:ilościowy:"
* $loinc#5198-7 "Wirus zapalenia wątroby typu C Ab:stężenie w jednostkach umownych:punkt w czasie:surowica:ilościowy:metoda immunologiczna"
* $loinc#5822-2 "Yeast [#/area] in Urine sediment by Microscopy high power field"
* $loinc#32356-8 "Yeast [Presence] in Urine sediment by Light microscopy"
* $loinc#21033-6 "Yeast.budding [Presence] in Urine sediment"
* $loinc#41865-7 "Yeast.hyphae [Presence] in Urine sediment by Light microscopy"
* $loinc#41863-2 "Yeast.pseudohyphae [Presence] in Urine sediment by Light microscopy"
* $loinc#2500-7 "Zdolność wiązania żelaza:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#14800-7 "Zdolność wiązania żelaza:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#2498-4 "Żelazo:stężenie masowe:punkt w czasie:surowica lub osocze:ilościowy:"
* $loinc#14798-3 "Żelazo:stężenie molowe:punkt w czasie:surowica lub osocze:ilościowy:"
