CodeSystem: SsidlTestedMaterialTypeCS
Id: ssidl-testedMaterialType-CS
Title: "Słownik materiałów badanych"
Description: "Uzupełniający (dla LOINC) słownik materiałów badanych (słownik własny SSIDL)"
* ^url = "http://loinc-ssidl.umed.pl/fhir/ig/ssidl/CodeSystem/ssidl-testedMaterialType-CS"
* #KREDTA "Krew pełna (EDTA)"
* #OSCYTR "Osocze cytrynianowe"
* #OSEDTA "Osocze EDTA"
* #OSHEPAR "Osocze heparynowe"
* #OSFLUOR "Osocze fluorkowe"
* #WYMAZ "Wymaz"
* #KRWHJW "Krew włośniczkowa heparynizowana stabilizowana jonami wapnia"
* #FRAGTK "Fragmenty tkankowe"
* #PLOWOD "Płyn owodniowy"
* #KRPOSIEW "Krew pełna (posiew krwi)"
* #MOCZSR "Mocz (środkowy strumień)"
* #MOCZCEW "Mocz (cewnikowany)"
* #MOCZNNADL "Mocz (nakłucie nadłonowe)"
* #BIOPTAT "Bioptat"
* #KRPCYTR41 "Krew pełna (cytrynian 4:1)"
* #WYMODB "Wymaz z odbytu"
* #WYMPPOCH "Wymaz z przedsionka pochwy"
* #WYMGARD "Wymaz z gardła"
* #WYMPNOS "Wymaz z przedsionka nosa"
* #WYMSZMAC "Wymaz z szyjki macicy"
* #KRPHEPLIT "Krew pełna (heparyna litowa)"
* #WYMNOSGARD "Wymaz z nosogardła"
* #KRPHJW "Krew pełna (heparyna stabilizowana jonami wapnia)"
* #WYMBSJU "Wymaz: z błony śluzowej jamy ustnej"
* #BSZKHEPLIT "Bioptat: Szpik kostny (z heparyną litową)"

