CodeSystem: SsidlMethodTypeCS
Id: ssidl-methodType-CS
Title: "Słownik własny metod oznaczeń laboratoryjnych (SSIDL)"
Description: "Kody metod oznaczen laboratoryjnych (słownik własny SSIDL uzupełniający do LOINC Part)"
* ^url = "http://loinc-ssidl.umed.pl/fhir/ig/ssidl/CodeSystem/ssidl-methodType-CS"
* #WSPRCHRCIECZ "wysokosprawna chromatografia cieczowa"
* #BIS1 "kreatynina-wzór (BIS1)/1,73m2"
* #MDRD "kreatynina-wzór (MDRD)/1,73 m2"
* #SEKWENC "sekwencjonowanie"
* #SUBCHROM "metoda z substratem chromogennym"
* #AGLUT "metoda aglutynacji"
* #PREPMOKRO "preparatyka na mokro"
* #SZPODSTSTEZ "szacowanie na podstawie stężenia w surowicy lub osoczu"
* #BARGRAM "barwienie metodą Grama"
* #OCORGAN "ocena organoleptyczna"
* #ZLICZWIZ "zliczanie wizualne"
* #IZOLAT "izolat"
* #CYTPRZEP "cytometria przepływowa"
* #MIC "minimalne stężenie hamujące (MIC)"
* #MANUAL "metoda manualna"
* #SZIMM "szybka metoda immunologiczna"
* #SPEKFOTOM "spektrofotometria"
* #POCHTKRZEP "pochodna testu krzepnięcia"
* #PARWYLICZ "parametr wyliczony"
* #MIKMAC "mikromacierz"
* #SEDYM "metoda sedymentacyjna"
* #POTW "metoda potwierdzająca"
* #KOAG "metoda koagulometryczna"
* #ISE "metoda jonoselektywna (ISE)"
* #IMTURB "metoda immunoturbidymetryczna"
* #IMCHEM "metoda immunochemiczna"
* #HOBEZTL "hodowla beztlenowa"
* #MALDITOF "spektrometria masowa z jonizacją laserową (MALDI-TOF)"
* #TPSCHKOL "test paskowy (sucha chemia, kolorymetria)"
* #TRVDRL "test reaginowy VDRL"
* #TRRPR "test reaginowy RPR"