CodeSystem: SsidlReasonForTestTypeCS
Id: ssidl-reasonForTestType-CS
Title: "Słownik typów celu badania"
Description: "Słownik typów celu badania (słownik własny SSIDL)"
* ^url = "http://loinc-ssidl.umed.pl/fhir/ig/ssidl/CodeSystem/ssidl-reasonForTestType-CS"
* #ROZP "Rozpoznanie"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "1"
* #WYKL "Wykluczenie"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "2"
* #WYKR "Wykrywanie (badanie przesiewowe)"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "3"
* #ROZN "Różnicowanie"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "4"
* #OZAAW "Ocena zaawansowania"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "5"
* #MONIT "Monitorowanie"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "6"
* #ORZECZ "Orzecznictwo"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "7"
* #STRARYZ "Stratyfikacja ryzyka"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "24"
* #INNE "Inne" // Czy da się uniknąć tej pozycji?
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "25"