CodeSystem: SsidlSpecimenHandlingCodeCS
Id: ssidl-specimenHandlingCode-CS
Title: "Typy czynników przedanalitycznych wg bazy wiedzy SSIDL"
Description: "Typy czynników przedanalitycznych zdefiniowane w bazie wiedzy SSIDL"
* ^url = "http://loinc-ssidl.umed.pl/fhir/ig/ssidl/CodeSystem/ssidl-specimenHandlingCode-CS"
* #PRZYGPAC "Przygotowanie pacjenta"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "1"
* #RMATBAD "Rodzaj materiału badanego"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "2"
* #WARTRANS "Warunki transportu"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "3"
* #WARWIR "Warunki wirowania"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "4"
* #STABPIERW "Stabilność w materiale pierwotnym"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "5"
* #STABWTOR "Stabilność w materiale wtórnym"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "6"
* #INTER "Interferencje"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "7"
* #SPEC "Specjalne"
  * ^designation[0].use = $designation-use#BWApp "Identyfikator pozycji słownika w aplikacji do tworzenia bazy wiedzy SSIDL"
  * ^designation[=].value = "8"
